import {
  buildSelectedSplitClosure,
  polygonToConstraints,
} from "@/engine/splitClosure";
import type {
  SplitClosureStep,
  SplitCutSpec,
} from "@/engine/splitClosure";
import type { Point2D, Scene } from "@/engine/types";
import type {
  VisualizationDefinition,
  VisualizationStage,
} from "@/visualizations/types";

const viewport: Scene["viewport"] = {
  x: [-1, 8],
  y: [-1, 7.5],
};

const initialVertices: Point2D[] = [
  [0, 0],
  [6.5, 0],
  [6.2, 1.5],
  [5.4, 3.2],
  [3.5, 5.6],
  [1.2, 6.2],
  [0, 5.5],
];

const initialConstraints = polygonToConstraints(initialVertices, {
  idPrefix: "split-closure-initial",
  labelPrefix: "P facet",
});

const cuts: SplitCutSpec[] = [
  {
    id: "vertical-right",
    pi: [1, 0],
    pi0: 6,
    title: "Remove the fractional right cap",
    description:
      "The split x₁ ≤ 6 or x₁ ≥ 7 removes the protrusion with 6 < x₁ < 7.",
    color: "#e27c89",
  },
  {
    id: "horizontal-top",
    pi: [0, 1],
    pi0: 5,
    title: "Cut across the upper cap",
    description:
      "The split x₂ ≤ 5 or x₂ ≥ 6 attacks the fractional top of the relaxation.",
    color: "#f49a4a",
  },
  {
    id: "diagonal-sum",
    pi: [1, 1],
    pi0: 8,
    title: "Use a diagonal split",
    description:
      "The split coordinate is x₁+x₂, so the forbidden strip is diagonal in the original plane.",
    color: "#8f88dc",
  },
  {
    id: "steeper-diagonal",
    pi: [1, 2],
    pi0: 13,
    title: "Use a steeper diagonal",
    description:
      "The final displayed split removes a fractional corner that survives the earlier directions.",
    color: "#79c9c0",
  },
];

const closure = buildSelectedSplitClosure({
  initialConstraints,
  viewport,
  title: "Displayed split closure",
  description:
    "Intersect the split polyhedra generated by four relevant split disjunctions.",
  cuts,
});

function formatPi(pi: Point2D): string {
  return `(${pi[0]}, ${pi[1]})`;
}

function formatLinearForm(pi: Point2D): string {
  const terms = [
    { coefficient: pi[0], variable: "x₁" },
    { coefficient: pi[1], variable: "x₂" },
  ].filter(({ coefficient }) => coefficient !== 0);

  return terms
    .map(({ coefficient, variable }, index) => {
      const magnitude = Math.abs(coefficient);
      const term = `${magnitude === 1 ? "" : magnitude}${variable}`;
      if (index === 0) return coefficient < 0 ? `−${term}` : term;
      return coefficient < 0 ? ` − ${term}` : ` + ${term}`;
    })
    .join("");
}

function scene(
  constraints: Scene["constraints"],
  overrides: Partial<Scene> = {},
): Scene {
  return {
    viewport,
    constraints,
    showGrid: true,
    showConstraints: true,
    showFeasibleRegion: true,
    showVertices: true,
    showLattice: true,
    ...overrides,
  };
}

function splitStages(step: SplitClosureStep): VisualizationStage[] {
  const cut = step.cut;
  const linearForm = formatLinearForm(cut.pi);
  const prefix = `closure-1-split-${step.splitIndex}`;

  return [
    {
      id: `${prefix}-project`,
      kicker: `Split ${step.splitIndex} · Projection`,
      title: `Project P onto π = ${formatPi(cut.pi)}`,
      description:
        "The closure input is projected onto the one-dimensional split coordinate πᵀx.",
      formula: "projₚᵢ(x) = (πᵀx / ‖π‖²)π",
      insight: cut.description,
      scene: scene(step.closureBaseConstraints, {
        showConstraints: false,
        showFeasibleRegion: false,
        showVertices: false,
        splitProjection: {
          pi: cut.pi,
          pi0: cut.pi0,
          phase: "project-polyhedron",
          showGuides: true,
          color: cut.color,
          stripColor: "#e27c89",
        },
      }),
      navigation: { closure: 1, split: step.splitIndex },
    },
    {
      id: `${prefix}-interval`,
      kicker: `Split ${step.splitIndex} · Forbidden interval`,
      title: "Reveal the lattice-free interval",
      description:
        `No integer point can have ${linearForm} strictly between ${cut.pi0} and ${cut.pi0 + 1}.`,
      formula: `${cut.pi0} < ${linearForm} < ${cut.pi0 + 1}`,
      insight:
        "The one-dimensional picture isolates exactly which projected values are forbidden.",
      scene: scene(step.closureBaseConstraints, {
        showGrid: false,
        showConstraints: false,
        showFeasibleRegion: false,
        showVertices: false,
        splitProjection: {
          pi: cut.pi,
          pi0: cut.pi0,
          phase: "projected-strip",
          color: cut.color,
          stripColor: "#e27c89",
        },
      }),
      navigation: { closure: 1, split: step.splitIndex },
    },
    {
      id: `${prefix}-lift`,
      kicker: `Split ${step.splitIndex} · Lift`,
      title: "Lift the interval back into the plane",
      description:
        "The interval endpoints become two parallel lines. Their inverse image is the forbidden strip in the original space.",
      formula: `${cut.pi0} < ${linearForm} < ${cut.pi0 + 1}`,
      insight:
        "Projection simplifies the split; lifting shows the full region removed from the polyhedron.",
      scene: scene(step.closureBaseConstraints, {
        showVertices: false,
        splitProjection: {
          pi: cut.pi,
          pi0: cut.pi0,
          phase: "lift-strip",
          color: cut.color,
          stripColor: "#e27c89",
        },
      }),
      navigation: { closure: 1, split: step.splitIndex },
    },
    {
      id: `${prefix}-remove`,
      kicker: `Split ${step.splitIndex} · Disjunction`,
      title: cut.title,
      description:
        "The open strip fades away. The two closed sides survive and are then convexified.",
      formula: `${linearForm} ≤ ${cut.pi0}  ∨  ${linearForm} ≥ ${cut.pi0 + 1}`,
      insight:
        `This split polyhedron removes ${step.splitRemovedArea.toFixed(2)} square units from the closure input.`,
      scene: scene(step.closureBaseConstraints, {
        showConstraints: false,
        showFeasibleRegion: false,
        showVertices: false,
        splitProjection: {
          pi: cut.pi,
          pi0: cut.pi0,
          phase: "remove-strip",
          color: cut.color,
          stripColor: "#e27c89",
        },
      }),
      navigation: { closure: 1, split: step.splitIndex },
    },
    {
      id: `${prefix}-split-polyhedron`,
      kicker: `Split ${step.splitIndex} · Convexify`,
      title: "Construct this split polyhedron",
      description:
        "Convexifying the two surviving pieces gives the polyhedron associated with this one split.",
      formula: "P⁽π,π₀⁾ = conv(P₁ ∪ P₂)",
      insight:
        "A split closure is obtained by intersecting such split polyhedra, not by choosing only one of them.",
      scene: scene(step.closureBaseConstraints, {
        showConstraints: false,
        showFeasibleRegion: false,
        showVertices: false,
        splitProjection: {
          pi: cut.pi,
          pi0: cut.pi0,
          phase: "split-hull",
          color: cut.color,
          stripColor: "#e27c89",
        },
      }),
      navigation: { closure: 1, split: step.splitIndex },
    },
    {
      id: `${prefix}-intersection`,
      kicker: `Split ${step.splitIndex} · Accumulate`,
      title: `Intersect the first ${step.splitIndex} split polyhedra`,
      description:
        "The displayed closure keeps only points that survive every split considered so far.",
      formula: `S${step.splitIndex} = S${step.splitIndex - 1} ∩ P⁽π,π₀⁾`,
      insight:
        `This split tightens the accumulated intersection by ${step.accumulatedRemovedArea.toFixed(2)} square units.`,
      scene: scene(step.afterIntersectionConstraints, {
        showIntegerHull: true,
      }),
      navigation: {
        closure: 1,
        split: step.splitIndex,
        milestone: "split",
      },
    },
  ];
}

const stages: VisualizationStage[] = [
  {
    id: "initial-polyhedron",
    kicker: "01 · Initial relaxation",
    title: "Start with a fractional polyhedron",
    description:
      "Each relevant split produces its own split polyhedron. Their intersection is the displayed finite description of the split closure.",
    formula: "Pˢᵖˡⁱᵗ = ⋂(π,π₀) P⁽π,π₀⁾",
    insight:
      "Use Detail to watch every animation, Splits to jump between accumulated cuts, or Closures to jump directly to the result.",
    scene: scene(initialConstraints, {
      showIntegerHull: true,
    }),
  },
  ...closure.steps.flatMap(splitStages),
  {
    id: "split-closure-result",
    kicker: "Result · Split closure",
    title: "The split polyhedra meet",
    description:
      "The final displayed region is the intersection of all split polyhedra included in this lesson.",
    formula: "S = P⁽π¹,π₀¹⁾ ∩ ··· ∩ P⁽π⁴,π₀⁴⁾",
    insight:
      "The mathematical split closure intersects over every admissible split; the animation exposes a finite relevant subfamily one split at a time.",
    scene: scene(closure.afterConstraints, {
      showIntegerHull: true,
    }),
    navigation: { closure: 1, milestone: "closure" },
  },
];

const visualization: VisualizationDefinition = {
  id: "split-closure",
  title: "Split Closure",
  shortTitle: "Split closure",
  chapter: "Cutting planes",
  order: 2,
  description:
    "Inspect individual split disjunctions and then intersect their split polyhedra to build a split closure.",
  difficulty: "Advanced",
  duration: 18,
  accent: "#8f88dc",
  controls: {
    constraints: false,
    lattice: true,
    vertices: true,
    labels: true,
  },
  stages,
  proof: {
    title: "Why does the closure preserve every integer point?",
    steps: [
      "For integral π and an integer point x, the value πᵀx is integral.",
      "No integer value lies strictly between π₀ and π₀+1.",
      "Every integer point therefore survives each individual split disjunction.",
      "Each split polyhedron contains all integer feasible points.",
      "Their intersection still contains all integer feasible points while removing fractional regions.",
    ],
  },
};

export default visualization;
