import { lemma51ProofExample } from "@/visualizations/helpers/proof-guided-extreme-ray-examples";
import type { VisualizationDefinition } from "@/visualizations/types";

const visualization: VisualizationDefinition = {
  id: "lemma-51-proof-walkthrough",
  title: "Lemma 51 — Proof Walkthrough",
  shortTitle: "Lemma 51 proof",
  chapter: "Extreme-ray proximity",
  order: 8,
  description:
    "Follow the proof in the notes: fix the multiplier sign cone, rule out an integral summand by domination, then invoke Carathéodory and conclude μk<1 and ‖u‖∞≤mΔ.",
  difficulty: "Advanced",
  duration: 18,
  accent: "#e27c89",
  controls: { constraints: true, grid: true, lattice: true, vertices: false, labels: true },
  stages: lemma51ProofExample.stages,
  proof: {
    title: "Lemma 51 in the order used by the lecture notes",
    steps: [
      "Fix M⁻ and M⁺ from the signs of u and form the cone C={w:wᵀA_C=0, w≤0 on M⁻, w≥0 on M⁺}.",
      "Let r¹,…,rᵗ be the primitive integral extreme rays of C; Lemma 32 gives ‖rᵏ‖∞≤Δ.",
      "First rule out case (a): if u=v+w with nonzero integral v∈C, then u and w have the same relevant fractional part.",
      "Because w⁺≤u⁺ and w⁻≤u⁻, the split inequality generated by w dominates the one generated by u, contradicting undominatedness.",
      "Now apply Carathéodory: u=Σₖ∈Kμₖrᵏ with |K|≤m.",
      "Any μₖ≥1 would recreate case (a), so every μₖ<1.",
      "Finally ‖u‖∞≤Σμₖ‖rᵏ‖∞≤mΔ.",
    ],
  },
};

export default visualization;
