import { lemma51ExplicitConeStages } from "@/visualizations/helpers/explicit-proximity-cones";
import { lemma51ProofExample } from "@/visualizations/helpers/proof-guided-extreme-ray-examples";
import type { VisualizationDefinition } from "@/visualizations/types";

const stages = [
  ...lemma51ExplicitConeStages,
  ...lemma51ProofExample.stages.slice(1),
];

const visualization: VisualizationDefinition = {
  id: "lemma-51-proof-walkthrough",
  title: "Lemma 51 — Proof Walkthrough",
  shortTitle: "Lemma 51 proof",
  chapter: "Extreme-ray proximity",
  order: 9,
  description:
    "First draw the actual lower-dimensional multiplier cone in w-space, identify its primitive extreme rays, and only then switch to coefficient coordinates for the domination and Carathéodory argument.",
  difficulty: "Advanced",
  duration: 22,
  accent: "#e27c89",
  controls: { constraints: true, grid: true, lattice: true, vertices: true, labels: true },
  stages,
  proof: {
    title: "Lemma 51 in the order used by the lecture notes",
    steps: [
      "Fix M⁻ and M⁺ from the signs of u and form the cone C={w:wᵀA_C=0, w≤0 on M⁻, w≥0 on M⁺}.",
      "Let r¹,…,rᵗ be the primitive integral extreme rays of C; Lemma 32 gives ‖rᵏ‖∞≤Δ.",
      "First rule out case (a): if u=v+w with nonzero integral v∈C, then u and w have the same relevant fractional part.",
      "Because w⁺≤u⁺ and w⁻≤u⁻, the split inequality generated by w dominates the one generated by u, contradicting undominatedness.",
      "Now apply Carathéodory: u=Σₖ∈Kμₖrᵏ with |K|≤m.",
      "Any μₖ≥1 would recreate case (a), so every μₖ<1.",
      "Finally ‖u‖∞≤Σμₖ‖rᵏ‖∞≤mΔ.",
    ],
  },
};

export default visualization;
