import type { Point2D, Primitive, Scene } from "@/engine/types";
import type {
  VisualizationDefinition,
  VisualizationExample,
  VisualizationStage,
} from "@/visualizations/types";

const optimizationConstraints: Scene["constraints"] = [
  { id: "left", a: -1, b: 0, limit: 0, label: "x₁≥0", color: "#79c9c0" },
  { id: "bottom", a: 0, b: -1, limit: 0, label: "x₂≥0", color: "#79c9c0" },
  { id: "right", a: 1, b: 0, limit: 5, label: "x₁≤5", color: "#8f88dc" },
  { id: "top", a: 0, b: 1, limit: 4, label: "x₂≤4", color: "#8f88dc" },
  { id: "slope", a: 1, b: 1, limit: 7, label: "x₁+x₂≤7", color: "#f49a4a" },
];

const z: Point2D = [1, 1];
const optimum: Point2D = [5, 2];
const localImprovement: Point2D = [2, 1];

function optimizationScene(overrides: Partial<Scene> = {}): Scene {
  return {
    viewport: { x: [-0.6, 5.7], y: [-0.6, 4.8] },
    constraints: optimizationConstraints,
    showGrid: true,
    showConstraints: true,
    showFeasibleRegion: true,
    showVertices: true,
    showLattice: true,
    axisLabels: { x: "x₁", y: "x₂" },
    caption: {
      primary: "Pentagonal integer polytope with Δ=1",
      secondary: "maximize c=(2,1); unique optimum is the vertex (5,2)",
    },
    ...overrides,
  };
}

function orthantScene(primitives: Primitive[], overrides: Partial<Scene> = {}): Scene {
  return {
    viewport: { x: [-0.6, 5.4], y: [-0.6, 3.6] },
    constraints: [
      { id: "u1-positive", a: -1, b: 0, limit: 0, label: "u₁≥0", color: "#f49a4a" },
      { id: "u2-positive", a: 0, b: -1, limit: 0, label: "u₂≥0", color: "#8f88dc" },
    ],
    showGrid: true,
    showConstraints: true,
    showFeasibleRegion: true,
    showVertices: false,
    showLattice: true,
    axisLabels: { x: "u₁", y: "u₂" },
    primitives,
    caption: {
      primary: "Sign-compatible displacement cone",
      secondary: "primitive rays e₁,e₂ have norm Δ=1",
    },
    ...overrides,
  };
}

const vertexImprovementStages: VisualizationStage[] = [
  {
    id: "t35-pentagon-start",
    kicker: "Theorem 35 · Nonoptimal vertex",
    title: "Start at a feasible integer point below the optimal vertex",
    description:
      "The natural pentagon has unique optimum ŷ=(5,2), a vertex. The current integer point z=(1,1) is feasible but not optimal for c=(2,1).",
    formula: "cᵀz=3<12=cᵀŷ",
    insight:
      "The theorem will not jump all the way to the optimum. It extracts a bounded local improvement from the displacement toward it.",
    scene: optimizationScene({
      objective: { vector: [2, 1], label: "c=(2,1)" },
      primitives: [
        { kind: "point", at: z, label: "current integer point z", style: "integer" },
        { kind: "point", at: optimum, label: "unique optimal vertex ŷ", style: "optimum" },
      ],
    }),
  },
  {
    id: "t35-pentagon-displacement",
    kicker: "Theorem 35 · Distant witness",
    title: "The optimal vertex certifies an improving displacement",
    description:
      "The vector ŷ−z=(4,1) lies in a sign-compatible cone. It proves that improving feasible integral displacements exist, but it is much longer than necessary.",
    formula: "ŷ−z=(4,1)",
    insight:
      "The far optimum is a witness of nonemptiness, not the move ultimately returned by the theorem.",
    scene: optimizationScene({
      primitives: [
        { kind: "point", at: z, label: "z", style: "integer" },
        { kind: "point", at: optimum, label: "optimal vertex ŷ", style: "optimum" },
        { kind: "vector", from: z, to: optimum, label: "long improving displacement", color: "#8f88dc", animate: true },
      ],
    }),
  },
  {
    id: "t35-pentagon-cone",
    kicker: "Theorem 35 · Extreme rays",
    title: "Translate z to the origin and expose short primitive directions",
    description:
      "In displacement coordinates, the relevant cone is generated by e₁ and e₂. The long vector (4,1) decomposes as four horizontal primitive steps and one vertical primitive step.",
    formula: "ŷ−z=4e₁+e₂",
    insight:
      "Lemma 32 says every primitive extreme ray has norm at most Δ=1 in this example.",
    scene: orthantScene([
      { kind: "vector", from: [0, 0], to: [5, 0], label: "u¹=e₁", color: "#f49a4a", animate: true },
      { kind: "vector", from: [0, 0], to: [0, 3], label: "u²=e₂", color: "#8f88dc", animate: true },
      { kind: "vector", from: [0, 0], to: [4, 1], label: "ŷ−z", color: "#e27c89", animate: true },
      { kind: "point", at: [1, 0], label: "primitive e₁", style: "integer" },
      { kind: "point", at: [0, 1], label: "primitive e₂", style: "integer" },
    ]),
  },
  {
    id: "t35-pentagon-short-ray",
    kicker: "Theorem 35 · Improving ray branch",
    title: "One primitive extreme-ray step already improves",
    description:
      "The horizontal ray has cᵀe₁=2>0. Hence y=z+e₁=(2,1) is feasible, integral, and strictly better, although it is not claimed to be globally optimal.",
    formula: "y=z+e₁=(2,1),   cᵀy=5>3=cᵀz",
    insight:
      "The local certificate is a better integer point, not necessarily an optimum. The actual optimum remains the far vertex (5,2).",
    scene: optimizationScene({
      primitives: [
        { kind: "point", at: z, label: "z", style: "integer" },
        { kind: "point", at: localImprovement, label: "better integer point y", style: "integer", animateFrom: z },
        { kind: "point", at: optimum, label: "optimal vertex ŷ", style: "optimum" },
        { kind: "vector", from: z, to: localImprovement, label: "u¹=e₁", color: "#f49a4a", animate: true },
      ],
    }),
  },
  {
    id: "t35-pentagon-local-box",
    kicker: "Theorem 35 · nΔ neighborhood",
    title: "The global failure is witnessed inside a small local box",
    description:
      "Here n=2 and Δ=1, so the theorem guarantees some improvement within radius two around z. The displayed witness is only one unit away.",
    formula: "‖y−z‖∞=1≤nΔ=2",
    insight:
      "The nΔ box converts global nonoptimality into a finite local search certificate.",
    scene: optimizationScene({
      primitives: [
        {
          kind: "polygon",
          points: [[-1, -1], [3, -1], [3, 3], [-1, 3]],
          label: "‖x−z‖∞≤nΔ",
          style: "integer-hull",
          fromPoints: [z, z, z, z],
        },
        { kind: "point", at: z, label: "z", style: "integer" },
        { kind: "point", at: localImprovement, label: "local improving y", style: "integer" },
        { kind: "point", at: optimum, label: "global optimum vertex", style: "optimum" },
        { kind: "vector", from: z, to: localImprovement, label: "local certificate", color: "#f49a4a", animate: true },
      ],
    }),
  },
];

const skewConeConstraints: Scene["constraints"] = [
  { id: "lower", a: 0, b: -1, limit: 0, label: "u₂≥0", color: "#8f88dc" },
  { id: "upper", a: -2, b: 1, limit: 0, label: "u₂≤2u₁", color: "#f49a4a" },
];

function skewConeScene(primitives: Primitive[], overrides: Partial<Scene> = {}): Scene {
  return {
    viewport: { x: [-0.6, 4.8], y: [-0.6, 4.8] },
    constraints: skewConeConstraints,
    showGrid: true,
    showConstraints: true,
    showFeasibleRegion: true,
    showVertices: false,
    showLattice: true,
    axisLabels: { x: "u₁", y: "u₂" },
    primitives,
    caption: {
      primary: "Skew displacement cone generated by (1,0) and (1,2)",
      secondary: "the fractional coefficients still sum to integral displacements",
    },
    ...overrides,
  };
}

const neutralRemovalStages: VisualizationStage[] = [
  {
    id: "t35-neutral-valid-setup",
    kicker: "Theorem 35 · Neutral-ray branch",
    title: "Use a decomposition whose total displacement is genuinely integral",
    description:
      "Let u¹=(1,0), u²=(1,2), and c=e₂. The coefficients 1.5 and 0.5 produce d=1.5u¹+0.5u²=(2,1), an integral improving displacement.",
    formula: "d=1.5(1,0)+0.5(1,2)=(2,1)∈ℤ²",
    insight:
      "This corrects the common pitfall that fractional ray coefficients need not individually produce fractional total displacement.",
    scene: skewConeScene([
      { kind: "vector", from: [0, 0], to: [4, 0], label: "u¹=(1,0)", color: "#8f88dc", animate: true },
      { kind: "vector", from: [0, 0], to: [2, 4], label: "u²=(1,2)", color: "#f49a4a", animate: true },
      { kind: "vector", from: [0, 0], to: [1.5, 0], label: "1.5u¹", color: "#8f88dc", animate: true },
      { kind: "vector", from: [1.5, 0], to: [2, 1], label: "0.5u²", color: "#f49a4a", animate: true },
      { kind: "point", at: [2, 1], label: "integral improving d", style: "integer" },
    ]),
  },
  {
    id: "t35-neutral-objective",
    kicker: "Theorem 35 · Identify neutral mass",
    title: "The first ray is neutral, while the second creates improvement",
    description:
      "For c=e₂, the horizontal primitive ray has zero objective gain, whereas u² raises the objective by two. Thus d is improving only because of its u² component.",
    formula: "cᵀu¹=0,   cᵀu²=2,   cᵀd=1>0",
    insight:
      "A coefficient at least one does not automatically yield an improving one-ray move; it may sit on a neutral direction.",
    scene: skewConeScene([
      { kind: "vector", from: [0, 0], to: [1.5, 0], label: "neutral 1.5u¹", color: "#8f88dc", animate: true },
      { kind: "vector", from: [1.5, 0], to: [2, 1], label: "improving 0.5u²", color: "#f49a4a", animate: true },
      { kind: "point", at: [2, 1], label: "d=(2,1)", style: "integer" },
      { kind: "line", from: [-0.4, 0], to: [4.6, 0], label: "cᵀu=0", style: "objective", color: "#e27c89" },
    ]),
  },
  {
    id: "t35-neutral-remove",
    kicker: "Theorem 35 · Remove one full ray",
    title: "Subtracting one neutral primitive ray preserves integrality and gain",
    description:
      "Remove one copy of u¹. The remainder d′=0.5u¹+0.5u²=(1,1) is still integral and has the same positive objective gain, but its total coefficient mass is one smaller.",
    formula: "d′=d−u¹=(1,1)∈ℤ²,   cᵀd′=cᵀd=1",
    insight:
      "This contradicts minimum ray mass. Therefore the hard case cannot contain a coefficient λⱼ≥1 on a nonimproving ray.",
    scene: skewConeScene([
      { kind: "point", at: [2, 1], label: "old d=(2,1)", style: "integer" },
      { kind: "point", at: [1, 1], label: "smaller d′=(1,1)", style: "optimum", animateFrom: [2, 1] },
      { kind: "vector", from: [2, 1], to: [1, 1], label: "subtract u¹", color: "#e27c89", animate: true },
      { kind: "vector", from: [0, 0], to: [0.5, 0], label: "0.5u¹", color: "#8f88dc", animate: true },
      { kind: "vector", from: [0.5, 0], to: [1, 1], label: "0.5u²", color: "#f49a4a", animate: true },
    ]),
  },
  {
    id: "t35-neutral-conclusion",
    kicker: "Theorem 35 · Coefficients below one",
    title: "Minimality leaves only fractional pieces of bounded rays",
    description:
      "Either a full ray is itself improving, or a full neutral/nonpositive ray can be removed. Consequently every coefficient in a minimum-mass improving decomposition is below one.",
    formula: "0≤λᵢ<1 ⇒ ‖d‖∞≤kΔ≤nΔ",
    insight:
      "The two proof branches now fit together without using a nonintegral displacement as the candidate.",
    scene: skewConeScene([
      {
        kind: "polygon",
        points: [[0, 0], [4, 0], [4, 4], [0, 4]],
        label: "universal nΔ region (n=2, Δ=2)",
        style: "integer-hull",
        fromPoints: [[0, 0], [0, 0], [0, 0], [0, 0]],
      },
      { kind: "vector", from: [0, 0], to: [0.5, 0], label: "λ₁u¹", color: "#8f88dc", animate: true },
      { kind: "vector", from: [0.5, 0], to: [1, 1], label: "λ₂u²", color: "#f49a4a", animate: true },
      { kind: "point", at: [1, 1], label: "integral minimal d′", style: "optimum" },
    ]),
  },
];

const vertexExample: VisualizationExample = {
  id: "pentagon-vertex-optimum",
  title: "Natural pentagon — local move toward a vertex optimum",
  description:
    "A nonoptimal integer point, a unique optimal vertex, and the one-step improving extreme-ray certificate inside the nΔ box.",
  stages: vertexImprovementStages,
};

const neutralExample: VisualizationExample = {
  id: "integral-neutral-removal",
  title: "Skew cone — valid neutral-ray removal",
  description:
    "A mathematically integral example of the second proof branch using rays (1,0) and (1,2).",
  stages: neutralRemovalStages,
};

const visualization: VisualizationDefinition = {
  id: "theorem-35-local-improvement",
  title: "Theorem 35 — A Nearby Improving Integer Point",
  shortTitle: "Theorem 35: local improvement",
  chapter: "Extreme-ray proximity",
  order: 3,
  description:
    "Use natural vertex geometry and a valid skew-cone decomposition to see why every nonoptimal integer point has a strictly better point within nΔ.",
  difficulty: "Advanced",
  duration: 19,
  accent: "#79c9c0",
  controls: {
    constraints: true,
    grid: true,
    lattice: true,
    vertices: true,
    labels: true,
  },
  stages: vertexImprovementStages,
  examples: [vertexExample, neutralExample],
  proof: {
    title: "Why every nonoptimal integer point has an nΔ-local improvement",
    steps: [
      "Choose an optimal integer vertex ŷ when convenient and form the sign-compatible cone containing ŷ−z.",
      "Let u¹,…,uᵗ be primitive integral extreme rays of the cone; Lemma 32 gives ‖uⁱ‖∞≤Δ.",
      "Among all improving integral displacements d=Σλᵢuᵢ, choose one minimizing Σλᵢ, and use Carathéodory to keep at most n rays.",
      "If λⱼ≥1 and cᵀuʲ>0, then z+uʲ is already a feasible improving integer point at distance at most Δ.",
      "If λⱼ≥1 and cᵀuʲ≤0, subtract one copy of uʲ. The resulting displacement remains integral, feasible, and strictly improving, contradicting minimality.",
      "Hence every remaining λᵢ<1, so ‖d‖∞≤Σλᵢ‖uᵢ‖∞≤kΔ≤nΔ.",
    ],
  },
};

export default visualization;
