import type {
  Mesh3D,
  PlanePatch3D,
  Point3D,
  Scene,
  Scene3D,
  Segment3D,
} from "@/engine/types";
import type { VisualizationDefinition, VisualizationStage } from "@/visualizations/types";

const boxFaces = [
  [0, 1, 2, 3],
  [4, 5, 6, 7],
  [0, 1, 5, 4],
  [1, 2, 6, 5],
  [2, 3, 7, 6],
  [3, 0, 4, 7],
];

function boxVertices(
  x: [number, number],
  y: [number, number],
  z: [number, number],
): Point3D[] {
  return [
    [x[0], y[0], z[0]],
    [x[1], y[0], z[0]],
    [x[1], y[1], z[0]],
    [x[0], y[1], z[0]],
    [x[0], y[0], z[1]],
    [x[1], y[0], z[1]],
    [x[1], y[1], z[1]],
    [x[0], y[1], z[1]],
  ];
}

function boxMesh(
  id: string,
  x: [number, number],
  y: [number, number],
  z: [number, number],
  options: Partial<Mesh3D> = {},
): Mesh3D {
  return {
    id,
    vertices: boxVertices(x, y, z),
    faces: boxFaces,
    style: "solid",
    ...options,
  };
}

const lpOptimum: Point3D = [2.6, 1.7, 2];
const arbitraryIpOptimum: Point3D = [0, 0, 2];
const shiftedIpOptimum: Point3D = [2, 1, 2];
const afterFirstRay: Point3D = [2.6, 0, 2];
const afterIntegerFirstRay: Point3D = [2, 0, 2];
const delta = 1;
const dimension = 3;

const topFace: PlanePatch3D = {
  id: "optimal-face",
  points: [[0, 0, 2], [4, 0, 2], [4, 4, 2], [0, 4, 2]],
  label: "optimal face cᵀx=2",
  color: "#f49a4a",
  opacity: 0.2,
};

function scene3D(configuration: Scene3D): Scene {
  return {
    viewport: { x: [0, 1], y: [0, 1] },
    constraints: [],
    showGrid: true,
    showLattice: true,
    showVertices: true,
    scene3D: configuration,
  };
}

function basePolyhedron(opacity = 0.18): Mesh3D {
  return boxMesh("proximity-box", [0, 4], [0, 4], [0, 2], {
    label: "P",
    color: "#79c9c0",
    opacity,
  });
}

function baseConfiguration(overrides: Partial<Scene3D> = {}): Scene3D {
  return {
    bounds: { x: [-0.5, 5], y: [-0.5, 5], z: [-0.35, 3.1] },
    axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
    camera: { yaw: -0.72, pitch: 0.48, distance: 7.5 },
    meshes: [basePolyhedron()],
    planes: [topFace],
    showGround: true,
    showIntegerLattice: true,
    integerAxes: ["x", "y", "z"],
    caption: {
      primary: "TU box example: Δ=1",
      secondary: "maximize c=e₃, so the whole top face is optimal",
    },
    ...overrides,
  };
}

const stages: VisualizationStage[] = [
  {
    id: "theorem34-optimal-face",
    kicker: "Theorem 34 · LP and IP optima",
    title: "The LP optimum may be fractional along an optimal face",
    description:
      "The objective maximizes x₃, so every point on the top face is LP-optimal. The rose point y* is fractional, while the dark lattice points on the same face are IP-optimal.",
    formula: "max{x₃:0≤x₁,x₂≤4, 0≤x₃≤2}",
    insight:
      "Proximity is not about rounding an arbitrary feasible point. It compares a chosen LP optimum with some integer optimum on the same objective level.",
    scene: scene3D(baseConfiguration({
      markers: [
        { id: "lp-optimum", at: lpOptimum, label: "LP optimum y*=(2.6,1.7,2)", style: "fractional" },
        { id: "ip-a", at: [0, 0, 2], label: "integer optimum", style: "integer" },
        { id: "ip-b", at: [2, 1, 2], label: "integer optimum", style: "integer" },
        { id: "ip-c", at: [3, 2, 2], label: "integer optimum", style: "integer" },
      ],
    })),
  },
  {
    id: "theorem34-arbitrary-optimum",
    kicker: "Theorem 34 · Start anywhere optimal",
    title: "Begin with any integer optimum x̂",
    description:
      "The proof starts from an arbitrary IP optimum, which may be far from y*. Here x̂=(0,0,2) lies on the same optimal face but is not the nearby integer optimum promised by the theorem.",
    formula: "d:=y*−x̂=(2.6,1.7,0)",
    insight:
      "The argument will move x̂ by integral extreme-ray steps without losing feasibility or optimality.",
    scene: scene3D(baseConfiguration({
      markers: [
        { id: "lp-optimum", at: lpOptimum, label: "y*", style: "fractional" },
        { id: "ip-start", at: arbitraryIpOptimum, label: "arbitrary x̂", style: "integer" },
      ],
      segments: [
        {
          id: "difference",
          from: arbitraryIpOptimum,
          to: lpOptimum,
          label: "d=y*−x̂",
          color: "#8f88dc",
          width: 3,
          animate: true,
        },
      ],
    })),
  },
  {
    id: "theorem34-sign-cone",
    kicker: "Theorem 34 · Sign-compatible cone",
    title: "The row comparison creates a cone of safe directions",
    description:
      "Relative to x̂ and y*, the active row signs define a cone C. In this box example, the relevant part of C is generated by e₁ and e₂ along the optimal top face.",
    formula: "C={u:A₁u≤0, A₂u≥0}",
    insight:
      "Remark 33 says that partial movement along the same nonnegative ray combination remains feasible.",
    scene: scene3D(baseConfiguration({
      meshes: [basePolyhedron(0.1)],
      markers: [
        { id: "start", at: arbitraryIpOptimum, label: "x̂", style: "integer" },
        { id: "end", at: lpOptimum, label: "y*", style: "fractional" },
      ],
      segments: [
        { id: "ray-e1", from: arbitraryIpOptimum, to: [3.5, 0, 2], label: "extreme ray u¹=e₁", color: "#f49a4a", width: 3, animate: true },
        { id: "ray-e2", from: arbitraryIpOptimum, to: [0, 3.5, 2], label: "extreme ray u²=e₂", color: "#8f88dc", width: 3, animate: true },
      ],
      caption: {
        primary: "Difference cone on the optimal face",
        secondary: "each primitive ray has ‖uⁱ‖∞=1=Δ",
      },
    })),
  },
  {
    id: "theorem34-caratheodory",
    kicker: "Theorem 34 · Carathéodory",
    title: "Use at most n extreme rays",
    description:
      "The displacement is written as a nonnegative combination of extreme rays. In the example, only two rays are needed although the ambient dimension is n=3.",
    formula: "y*−x̂=2.6e₁+1.7e₂,   k=2≤n",
    insight:
      "Lemma 32 bounds each ray by Δ; Carathéodory bounds how many ray directions must be summed.",
    scene: scene3D(baseConfiguration({
      meshes: [basePolyhedron(0.1)],
      markers: [
        { id: "start", at: arbitraryIpOptimum, label: "x̂", style: "integer" },
        { id: "corner", at: afterFirstRay, label: "x̂+2.6e₁", style: "optimum" },
        { id: "end", at: lpOptimum, label: "y*", style: "fractional" },
      ],
      segments: [
        { id: "lambda-one", from: arbitraryIpOptimum, to: afterFirstRay, label: "2.6u¹", color: "#f49a4a", width: 4, animate: true },
        { id: "lambda-two", from: afterFirstRay, to: lpOptimum, label: "1.7u²", color: "#8f88dc", width: 4, animate: true },
      ],
    })),
  },
  {
    id: "theorem34-strip-integer-parts",
    kicker: "Theorem 34 · Remove full ray steps",
    title: "Integer coefficients can be absorbed into x̂",
    description:
      "Because the rays are integral and objective-nondecreasing, two full e₁ steps and one full e₂ step move x̂ to another integer optimum x*. Only fractional remainders remain.",
    formula: "x*=x̂+2e₁+e₂,   y*−x*=0.6e₁+0.7e₂",
    insight:
      "This is the decisive reduction: replace a far integer optimum by a new one so every remaining coefficient is below one.",
    scene: scene3D(baseConfiguration({
      meshes: [basePolyhedron(0.1)],
      markers: [
        { id: "old", at: arbitraryIpOptimum, label: "old x̂", style: "integer" },
        { id: "integer-corner", at: afterIntegerFirstRay, label: "x̂+2e₁", style: "integer", animateFrom: arbitraryIpOptimum },
        { id: "new", at: shiftedIpOptimum, label: "new optimum x*", style: "optimum", animateFrom: afterIntegerFirstRay },
        { id: "lp", at: lpOptimum, label: "y*", style: "fractional" },
      ],
      segments: [
        { id: "integer-e1", from: arbitraryIpOptimum, to: afterIntegerFirstRay, label: "⌊2.6⌋e₁", color: "#f49a4a", width: 4, animate: true },
        { id: "integer-e2", from: afterIntegerFirstRay, to: shiftedIpOptimum, label: "⌊1.7⌋e₂", color: "#8f88dc", width: 4, animate: true },
        { id: "remainder", from: shiftedIpOptimum, to: lpOptimum, label: "fractional remainder", color: "#e27c89", width: 3, dashed: true, animate: true },
      ],
    })),
  },
  {
    id: "theorem34-proximity-box",
    kicker: "Theorem 34 · Sum the bounds",
    title: "At most n short fractional ray pieces remain",
    description:
      "The small violet box is the actual ℓ∞ remainder in this example. The general proof only uses λᵢ<1, k≤n, and ‖uᵢ‖∞≤Δ, producing the universal radius nΔ.",
    formula: "‖y*−x*‖∞≤Σᵢλᵢ‖uᵢ‖∞≤kΔ≤nΔ",
    insight:
      "The nΔ-box is obtained by adding at most n determinant-bounded ray fragments, each shorter than one full primitive step.",
    scene: scene3D({
      bounds: { x: [-0.5, 5], y: [-0.5, 5], z: [-0.35, 3.1] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.72, pitch: 0.48, distance: 7.5 },
      meshes: [
        basePolyhedron(0.08),
        boxMesh("actual-remainder-box", [2, 2.7], [1, 1.7], [1.9, 2.1], {
          label: "actual ‖y*−x*‖∞=0.7",
          color: "#8f88dc",
          opacity: 0.22,
          style: "split-hull",
          fromVertices: boxVertices([2.6, 2.6], [1.7, 1.7], [2, 2]),
        }),
      ],
      planes: [topFace],
      segments: [
        { id: "final-gap", from: shiftedIpOptimum, to: lpOptimum, label: "0.6e₁+0.7e₂", color: "#e27c89", width: 4, animate: true },
      ],
      markers: [
        { id: "x-star", at: shiftedIpOptimum, label: "x*", style: "optimum" },
        { id: "y-star", at: lpOptimum, label: "y*", style: "fractional" },
      ],
      showGround: true,
      showIntegerLattice: true,
      integerAxes: ["x", "y", "z"],
      caption: {
        primary: `Actual gap 0.7; theorem radius nΔ=${dimension * delta}`,
        secondary: "the illustrated box is the tighter example-specific remainder",
      },
    }),
  },
  {
    id: "theorem34-conclusion",
    kicker: "Theorem 34 · Proximity principle",
    title: "Every LP optimum has an integer optimum nearby",
    description:
      "Starting from any integer optimum, the proof repeatedly absorbs full integral ray steps. The final integer optimum is still feasible and optimal, but now differs from y* by fewer than n determinant-bounded primitive steps.",
    formula: "∀y*∈argmax(LP) ∃x*∈argmax(IP): ‖y*−x*‖∞≤nΔ",
    insight:
      "The theorem converts local arithmetic control of cone rays into a global LP–IP distance guarantee.",
    scene: scene3D(baseConfiguration({
      meshes: [basePolyhedron(0.12)],
      markers: [
        { id: "x-star", at: shiftedIpOptimum, label: "nearby IP optimum x*", style: "optimum" },
        { id: "y-star", at: lpOptimum, label: "chosen LP optimum y*", style: "fractional" },
      ],
      segments: [
        { id: "certificate", from: shiftedIpOptimum, to: lpOptimum, label: "distance ≤ nΔ", color: "#e27c89", width: 4, animate: true },
      ],
    })),
  },
];

const visualization: VisualizationDefinition = {
  id: "theorem-34-lp-ip-proximity",
  title: "Theorem 34 — LP–IP Proximity",
  shortTitle: "Theorem 34: proximity",
  chapter: "Extreme-ray proximity",
  order: 2,
  description:
    "Follow an arbitrary integer optimum toward a chosen fractional LP optimum by decomposing their difference into short integral extreme rays and stripping away full ray steps.",
  difficulty: "Advanced",
  duration: 18,
  accent: "#8f88dc",
  controls: {
    constraints: false,
    grid: true,
    lattice: true,
    vertices: true,
    labels: true,
  },
  stages,
  proof: {
    title: "Why the closest suitable integer optimum is at most nΔ away",
    steps: [
      "Fix an LP optimum y* and any IP optimum x̂, then partition the rows according to whether Aᵢy*<Aᵢx̂ or Aᵢy*≥Aᵢx̂.",
      "The resulting sign-compatible cone C contains y*−x̂, and complementary slackness implies cᵀu≥0 for every u∈C.",
      "Write y*−x̂=Σᵢ₌₁ᵏ λᵢuᵢ using primitive integral extreme rays; Carathéodory gives k≤n.",
      "Lemma 32 gives ‖uᵢ‖∞≤Δ for every ray.",
      "Whenever λⱼ≥1, move x̂ by ⌊λⱼ⌋uⱼ. Remark 33 preserves feasibility, integrality is preserved, and cᵀuⱼ≥0 preserves optimality.",
      "After absorbing all full ray steps, every remaining coefficient is below one.",
      "Hence ‖y*−x*‖∞≤Σλᵢ‖uᵢ‖∞≤kΔ≤nΔ.",
    ],
  },
};

export default visualization;
