import type { Marker3D, Mesh3D, Point2D, Point3D, Primitive, Scene3D } from "@/engine/types";
import type {
  VisualizationDefinition,
  VisualizationExample,
  VisualizationStage,
} from "@/visualizations/types";
import {
  LATTICE_FREE_COLORS as C,
  label2D,
  line2D,
  marker3D,
  point2D,
  polygon2D,
  scene2D,
  scene3D,
  segment3D,
} from "@/visualizations/helpers/lattice-free-scenes";

// -----------------------------------------------------------------------------
// 2D example from the notes: p=(3,5)
// -----------------------------------------------------------------------------

const p2: Point2D = [3, 5];
const h2D: Point2D[] = [
  [1, 0],
  [1, 1],
  [2, 2],
  [2, 3],
  [3, 4],
  [3, 5],
];
const basis2D: Point2D[] = [[1, 0], [1, 1], [2, 3], [3, 5]];
const cone2DViewport = { x: [-0.5, 8.8] as [number, number], y: [-0.5, 9.2] as [number, number] };
const cone2DPolygon: Point2D[] = [[0, 0], [8.5, 0], [8.5, 9], [5.4, 9]];

function cone2DLattice(): Primitive[] {
  const result: Primitive[] = [];
  for (let x = 0; x <= 8; x += 1) {
    for (let y = 0; y <= 9; y += 1) {
      if (5 * x >= 3 * y) result.push(point2D([x, y], undefined, "lattice"));
    }
  }
  return result;
}

function layerLines2D(maxLayer = 5): Primitive[] {
  const result: Primitive[] = [];
  for (let j = 1; j <= maxLayer; j += 1) {
    result.push(line2D([0, j], [8.5, j], `y=${j}`, C.muted, "assignment"));
  }
  return result;
}

function sceneFor2D(extra: Primitive[], secondary: string) {
  return scene2D(
    [
      polygon2D(cone2DPolygon, "C=cone((1,0),(3,5))", "feasible"),
      ...cone2DLattice(),
      line2D([0, 0], [8.5, 0], "e₁=(1,0)", C.orange, "constraint"),
      line2D([0, 0], [5.4, 9], "p=(3,5)", C.aqua, "constraint"),
      ...extra,
    ],
    {
      primary: "Parametric integral generating set · p=(3,5)",
      secondary,
    },
    { viewport: cone2DViewport },
  );
}

const stages2D: VisualizationStage[] = [
  {
    id: "parametric-2d-setup",
    kicker: "Chapter 21 · Parametric feasible set",
    title: "Start with the cone generated by e₁ and p=(3,5)",
    description:
      "This is the exact two-dimensional family from the notes. A lattice point (x,y) lies in the cone exactly when y≥0 and x≥(3/5)y.",
    formula: "F=cone((1,0),(3,5))∩ℤ² = {(x,y)∈ℤ²₊ : x≥3y/5}",
    insight:
      "At a fixed integer height y, the first lattice point of the cone is obtained by rounding the boundary coordinate 3y/5 upward.",
    scene: sceneFor2D([], "The slanted ray is p; every horizontal slice extends to the right from the cone boundary."),
  },
  {
    id: "parametric-2d-ceiling-points",
    kicker: "Construction · One residue representative per height",
    title: "The ceiling formula selects the leftmost lattice point on each residue layer",
    description:
      "For j=1,…,5, the point h_j=(⌈3j/5⌉,j) is the leftmost lattice point of C on the horizontal line y=j. Together with e₁ these points form the finite generating set H from the notes.",
    formula: "H={(1,0)}∪{(⌈3j/5⌉,j):j=1,…,5}",
    insight:
      "The ceiling is geometric: it moves the real boundary intersection horizontally to the first integer x-coordinate that still lies inside the cone.",
    scene: sceneFor2D(
      [
        ...layerLines2D(),
        ...h2D.slice(1).map((h, i) => point2D(h, `h${i + 1}=(${h[0]},${h[1]})`, "optimum")),
        point2D([1, 0], "e₁", "optimum"),
      ],
      "Each highlighted h_j is the first feasible lattice point on its horizontal layer.",
    ),
  },
  {
    id: "parametric-2d-residues",
    kicker: "Proof step 1 · Reduce y modulo p₂",
    title: "Only the residue of y modulo 5 matters",
    description:
      "For any (x,y)∈F write y=5n+j with j∈{0,1,2,3,4}. Moving down by n copies of p=(3,5) lands on the residue layer j.",
    formula: "y=5n+j  ⇒  (x,y)-n(3,5) has second coordinate j",
    insight:
      "This is why only finitely many h_j are needed although the cone has infinitely many horizontal lattice layers.",
    scene: sceneFor2D(
      [
        point2D([8, 7], "x=(8,7)", "integer"),
        line2D([8, 7], [5, 2], "subtract p=(3,5)", C.rose, "assignment"),
        point2D([5, 2], "same residue layer j=2", "fractional"),
        point2D([2, 2], "h₂=(2,2)", "optimum"),
      ],
      "Example: 7=1·5+2, so subtracting one p reduces the problem to the j=2 layer.",
    ),
  },
  {
    id: "parametric-2d-proof-decomposition",
    kicker: "Proof step 2 · Move to the leftmost lattice point",
    title: "The remaining horizontal distance is an integer multiple of e₁",
    description:
      "Because x is integral and x≥yp₁/p₂, after the residue reduction we have x=np₁+⌈jp₁/p₂⌉+i for some i∈ℤ₊. Hence every lattice point is generated by e₁, p, and one residue representative.",
    formula: "(x,y)=i(1,0)+n(3,5)+(⌈3j/5⌉,j)",
    insight:
      "For x=(8,7): 7=5+2 and 8=3+2+3, so (8,7)=3e₁+p+h₂.",
    scene: sceneFor2D(
      [
        point2D([2, 2], "h₂", "optimum"),
        line2D([2, 2], [5, 2], "+3e₁", C.orange, "assignment"),
        line2D([5, 2], [8, 7], "+p", C.aqua, "assignment"),
        point2D([8, 7], "(8,7)=3e₁+p+h₂", "optimum"),
      ],
      "The proof is literally a vertical residue reduction followed by a horizontal integer translation.",
    ),
  },
  {
    id: "parametric-2d-generating-vs-basis",
    kicker: "Important distinction from the notes",
    title: "H is a generating set; the integral basis can be strictly smaller",
    description:
      "The notes explicitly warn that the ceiling construction need not already be inclusion-minimal. For p=(3,5), h₂=(2,2)=2(1,1) and h₄=(3,4)=(1,1)+(2,3), so both are redundant.",
    formula: "basis={(1,0),(1,1),(2,3),(3,5)} ⊂ H",
    insight:
      "This is the subtle point hidden by the wording of the slide: the displayed formula gives a finite integral generating set, not automatically the integral basis.",
    scene: sceneFor2D(
      [
        ...h2D.map((h) => point2D(h, undefined, "integer")),
        ...basis2D.map((h, i) => point2D(h, i === 0 ? "integral basis" : undefined, "optimum")),
        line2D([1, 1], [2, 2], "2(1,1)", C.rose, "assignment"),
        line2D([1, 1], [3, 4], "+(2,3)", C.rose, "assignment"),
      ],
      "Highlighted points are the unique integral basis for this pointed cone; the other H-points are generated by them.",
    ),
  },
];

// -----------------------------------------------------------------------------
// Natural 3D analogue (not stated separately in the notes):
// C=cone(e1,e2,p), p=(2,3,5).
// The same residue argument gives
// H={e1,e2}∪{(ceil(2j/5),ceil(3j/5),j): j=1,...,5}.
// -----------------------------------------------------------------------------

const e1: Point3D = [1, 0, 0];
const e2: Point3D = [0, 1, 0];
const p3: Point3D = [2, 3, 5];
const h3D: Point3D[] = [
  [1, 1, 1],
  [1, 2, 2],
  [2, 2, 3],
  [2, 3, 4],
  [2, 3, 5],
];

function scale3(lambda: number, v: Point3D): Point3D {
  return [lambda * v[0], lambda * v[1], lambda * v[2]];
}

function truncatedCone3D(scale: number, id: string): Mesh3D {
  return {
    id,
    vertices: [[0, 0, 0], scale3(scale, e1), scale3(scale, e2), scale3(scale, p3)],
    faces: [[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]],
    label: "truncated C=cone(e₁,e₂,p)",
    color: C.lime,
    edgeColor: C.muted,
    opacity: 0.17,
    style: "ghost",
  };
}

function coneCoordinates3D(q: Point3D): [number, number, number] {
  const lambda3 = q[2] / 5;
  return [q[0] - 2 * lambda3, q[1] - 3 * lambda3, lambda3];
}

function coneLattice3D(scale: number): Marker3D[] {
  const result: Marker3D[] = [];
  const xMax = Math.ceil(2 * scale + scale);
  const yMax = Math.ceil(3 * scale + scale);
  const zMax = Math.ceil(5 * scale);
  for (let x = 0; x <= xMax; x += 1) {
    for (let y = 0; y <= yMax; y += 1) {
      for (let z = 0; z <= zMax; z += 1) {
        const q: Point3D = [x, y, z];
        const [l1, l2, l3] = coneCoordinates3D(q);
        if (l1 < -1e-9 || l2 < -1e-9 || l3 < -1e-9) continue;
        if (l1 + l2 + l3 > scale + 1e-9) continue;
        result.push(marker3D(`param3-lattice-${x}-${y}-${z}`, q, undefined, "integer", 0.038));
      }
    }
  }
  return result;
}

const bounds3D: Scene3D["bounds"] = { x: [-0.4, 6.2], y: [-0.4, 7.3], z: [-0.4, 10.6] };

function base3D(extraMarkers: Marker3D[] = [], extraSegments = [], caption?: { primary: string; secondary: string }) {
  return scene3D({
    bounds: bounds3D,
    axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
    camera: { yaw: 0.82, pitch: 0.48, distance: 12.2 },
    verticalScale: 0.62,
    meshes: [truncatedCone3D(2, "param3-cone")],
    markers: [...coneLattice3D(2), ...extraMarkers],
    segments: [
      segment3D("param3-e1", [0, 0, 0], scale3(3.5, e1), "e₁", C.orange),
      segment3D("param3-e2", [0, 0, 0], scale3(3.5, e2), "e₂", C.aqua),
      segment3D("param3-p", [0, 0, 0], p3, "p=(2,3,5)", C.violet),
      ...extraSegments,
    ],
    showAxes: true,
    showGround: true,
    showIntegerLattice: false,
    caption: caption ?? {
      primary: "Natural 3D analogue",
      secondary: "The cone is generated by two coordinate rays and p=(2,3,5).",
    },
  });
}

const stages3D: VisualizationStage[] = [
  {
    id: "parametric-3d-setup",
    kicker: "3D analogue · Same residue mechanism",
    title: "Replace the horizontal ray by the coordinate plane directions e₁,e₂",
    description:
      "A direct three-dimensional analogue is C=cone(e₁,e₂,p) with p=(2,3,5). At a fixed integer height z, feasibility means x₁≥2z/5 and x₂≥3z/5.",
    formula: "F=C∩ℤ³,   C=cone(e₁,e₂,(2,3,5))",
    insight:
      "Each horizontal z-layer is now a translated two-dimensional nonnegative orthant rather than a one-dimensional ray.",
    scene: base3D(),
  },
  {
    id: "parametric-3d-ceiling-corners",
    kicker: "3D construction · One lower-left corner per residue layer",
    title: "The ceiling formula rounds both boundary coordinates upward",
    description:
      "For j=1,…,5 define h_j=(⌈2j/5⌉,⌈3j/5⌉,j). This is the componentwise-minimal lattice point in the cone on the plane x₃=j. Every other lattice point on that layer is h_j+k₁e₁+k₂e₂.",
    formula: "H={e₁,e₂}∪{(⌈2j/5⌉,⌈3j/5⌉,j):j=1,…,5}",
    insight:
      "The 2D leftmost point becomes a 3D lower-left corner of an entire lattice quadrant.",
    scene: base3D(
      h3D.map((h, i) => marker3D(`param3-h-${i}`, h, `h${i + 1}`, "optimum", 0.085)),
      h3D.flatMap((h, i) => [
        segment3D(`param3-layer-x-${i}`, h, [h[0] + 2.0, h[1], h[2]], `h${i + 1}+ℤ₊e₁`, C.orange, { width: 2 }),
        segment3D(`param3-layer-y-${i}`, h, [h[0], h[1] + 2.0, h[2]], `h${i + 1}+ℤ₊e₂`, C.aqua, { width: 2 }),
      ]),
      {
        primary: "Residue-layer corners in ℝ³",
        secondary: "Each highlighted h_j anchors the integer quadrant on x₃=j.",
      },
    ),
  },
  {
    id: "parametric-3d-residue",
    kicker: "3D proof step 1 · Reduce x₃ modulo p₃",
    title: "Subtract copies of p until the third coordinate is a residue j∈{0,…,4}",
    description:
      "For x∈F write x₃=5n+j. Subtracting np preserves integrality and leaves the third coordinate j. The first two coordinates remain above their respective slanted cone boundaries.",
    formula: "x₃=5n+j  ⇒  x-np has third coordinate j",
    insight:
      "Exactly the same modular argument as in 2D survives; only the residual cross-section has one extra free coordinate direction.",
    scene: base3D(
      [
        marker3D("param3-x", [5, 6, 7], "x=(5,6,7)", "optimum", 0.1),
        marker3D("param3-residue", [3, 3, 2], "x-p=(3,3,2)", "fractional", 0.085),
        marker3D("param3-h2", [1, 2, 2], "h₂=(1,2,2)", "optimum", 0.09),
      ],
      [segment3D("param3-subtract", [5, 6, 7], [3, 3, 2], "−p", C.rose, { dashed: true })],
      {
        primary: "Reduce the vertical coordinate modulo five",
        secondary: "7=1·5+2, so the target is reduced to the j=2 layer.",
      },
    ),
  },
  {
    id: "parametric-3d-decomposition",
    kicker: "3D proof step 2 · Translate inside the residue layer",
    title: "The residual displacement is a nonnegative integer combination of e₁ and e₂",
    description:
      "On the j=2 layer, x-p=(3,3,2) differs from h₂=(1,2,2) by 2e₁+e₂. Therefore the original target is generated by the finite set H.",
    formula: "(5,6,7)=2e₁+e₂+p+h₂",
    insight:
      "This is the three-dimensional version of 'move to the leftmost lattice point'; now we move to the lower-left corner in two coordinate directions.",
    scene: base3D(
      [
        marker3D("param3-d-h2", [1, 2, 2], "h₂", "optimum", 0.09),
        marker3D("param3-d-a", [3, 2, 2], "h₂+2e₁", "integer", 0.075),
        marker3D("param3-d-b", [3, 3, 2], "+e₂", "integer", 0.075),
        marker3D("param3-d-x", [5, 6, 7], "+p=x", "optimum", 0.1),
      ],
      [
        segment3D("param3-d1", [1, 2, 2], [3, 2, 2], "+2e₁", C.orange),
        segment3D("param3-d2", [3, 2, 2], [3, 3, 2], "+e₂", C.aqua),
        segment3D("param3-d3", [3, 3, 2], [5, 6, 7], "+p", C.violet),
      ],
      {
        primary: "Explicit 3D integral decomposition",
        secondary: "Every coefficient in the displayed decomposition is a nonnegative integer.",
      },
    ),
  },
  {
    id: "parametric-3d-general-n",
    kicker: "Higher-dimensional pattern",
    title: "The same construction extends to cone(e₁,…,eₙ₋₁,p)",
    description:
      "This n-dimensional formula is a direct generalization of the proof in the notes: reduce the last coordinate modulo p_n, round each of the first n−1 boundary coordinates upward, and use the coordinate rays for the remaining integral slack.",
    formula:
      "H={e₁,…,eₙ₋₁}∪{(⌈jp₁/pₙ⌉,…,⌈jpₙ₋₁/pₙ⌉,j):j=1,…,pₙ}",
    insight:
      "The notes state only the two-dimensional version. The 3D scene shows exactly how the same residue-and-ceiling proof generalizes; minimality of H is still a separate question.",
    scene: base3D(
      h3D.map((h, i) => marker3D(`param3-general-${i}`, h, i === 0 ? "residue representatives" : undefined, "optimum", 0.08)),
      [],
      {
        primary: "General residue-and-ceiling template",
        secondary: "In n dimensions, each residue layer is generated from one rounded corner by e₁,…,eₙ₋₁.",
      },
    ),
  },
];

const examples: VisualizationExample[] = [
  {
    id: "parametric-generators-2d",
    title: "2D · exact p=(3,5) example from the notes",
    description: "The ceiling construction, its proof, and extraction of the actual integral basis.",
    stages: stages2D,
  },
  {
    id: "parametric-generators-3d",
    title: "3D · natural p=(2,3,5) analogue",
    description: "The same modular proof with two coordinate directions in every residue layer.",
    stages: stages3D,
  },
];

const visualization: VisualizationDefinition = {
  id: "parametric-integral-generating-set",
  title: "Parametric Integral Generating Sets — Residues and Ceiling Rounding",
  shortTitle: "Parametric generating set",
  chapter: "Integral generating sets",
  order: 0,
  description:
    "Visualizes the parametric cone F=cone((1,0),p)∩ℤ² from Chapter 21, the ceiling construction of its finite integral generating set, the complete residue-class proof, the p=(3,5) integral basis, and a rigorous higher-dimensional analogue.",
  difficulty: "Intermediate",
  duration: 16,
  accent: C.aqua,
  visualLabel: "Residue-layer geometry",
  insightLabel: "Why the ceiling formula works",
  controls: { grid: true, lattice: true, vertices: false, labels: true },
  stages: stages2D,
  examples,
  proof: {
    title: "Residue-and-ceiling proof",
    steps: [
      "For (x,y)∈cone((1,0),p)∩ℤ², write y=np₂+j with 0≤j<p₂.",
      "Cone membership gives x≥yp₁/p₂=np₁+jp₁/p₂. Since x is integral, x=np₁+⌈jp₁/p₂⌉+i for some i∈ℤ₊.",
      "Therefore (x,y)=i(1,0)+np+(⌈jp₁/p₂⌉,j), proving finite integral generation.",
      "For p=(3,5), H={(1,0),(1,1),(2,2),(2,3),(3,4),(3,5)}. Removing the decomposable points (2,2) and (3,4) leaves the integral basis {(1,0),(1,1),(2,3),(3,5)}.",
      "In the direct n-dimensional analogue cone(e₁,…,eₙ₋₁,p), reduce x_n modulo p_n and apply the same ceiling argument coordinatewise to obtain the displayed finite generating set.",
    ],
  },
};

export default visualization;
