import type {
  Marker3D,
  Mesh3D,
  Point2D,
  Point3D,
  Primitive,
  Scene3D,
  Segment3D,
} from "@/engine/types";
import type {
  VisualizationDefinition,
  VisualizationExample,
  VisualizationStage,
} from "@/visualizations/types";
import {
  LATTICE_FREE_COLORS as C,
  line2D,
  marker3D,
  point2D,
  polygon2D,
  scene2D,
  scene3D,
  segment3D,
} from "@/visualizations/helpers/lattice-free-scenes";

// Exact 2D example from Chapter 21: p=(3,5).
const H2: Point2D[] = [[1, 0], [1, 1], [2, 2], [2, 3], [3, 4], [3, 5]];
const B2: Point2D[] = [[1, 0], [1, 1], [2, 3], [3, 5]];
const conePolygon2D: Point2D[] = [[0, 0], [8.5, 0], [8.5, 9], [5.4, 9]];

function lattice2D(): Primitive[] {
  const result: Primitive[] = [];
  for (let x = 0; x <= 8; x += 1) {
    for (let y = 0; y <= 9; y += 1) {
      if (5 * x >= 3 * y) result.push(point2D([x, y], undefined, "lattice"));
    }
  }
  return result;
}

function base2D(extra: Primitive[], secondary: string) {
  return scene2D(
    [
      polygon2D(conePolygon2D, "C=cone((1,0),(3,5))", "feasible"),
      ...lattice2D(),
      line2D([0, 0], [8.5, 0], "e₁=(1,0)", C.orange, "constraint"),
      line2D([0, 0], [5.4, 9], "p=(3,5)", C.aqua, "constraint"),
      ...extra,
    ],
    {
      primary: "Parametric integral generating set · p=(3,5)",
      secondary,
    },
    { viewport: { x: [-0.5, 8.8], y: [-0.5, 9.2] } },
  );
}

const stages2D: VisualizationStage[] = [
  {
    id: "param-2d-cone",
    kicker: "Chapter 21 · Exact example from the notes",
    title: "The cone is sliced into horizontal integer layers",
    description:
      "For p=(3,5), F=cone((1,0),p)∩ℤ². At height y=j the real boundary is x=3j/5, so the first feasible integer x-coordinate is ⌈3j/5⌉.",
    formula: "F={(x,y)∈ℤ²₊:x≥3y/5}",
    insight: "The ceiling in H is simply the first lattice point to the right of the slanted boundary.",
    scene: base2D([], "Every horizontal slice is a ray starting at x=3y/5."),
  },
  {
    id: "param-2d-H",
    kicker: "Construction of H",
    title: "Choose one residue representative on each layer j=1,…,5",
    description:
      "The highlighted points are exactly the ceiling construction from the notes. The point for j=5 is p itself.",
    formula: "H={(1,0)}∪{(⌈3j/5⌉,j):j=1,…,5}",
    insight: "Only five nonzero residue layers are needed because y will later be reduced modulo p₂=5.",
    scene: base2D(
      [
        ...[1, 2, 3, 4, 5].map((j) => line2D([0, j], [8.5, j], `y=${j}`, C.muted)),
        ...H2.map((h, i) => point2D(h, i === 0 ? "e₁" : `h${i}`, "optimum")),
      ],
      "H={(1,0),(1,1),(2,2),(2,3),(3,4),(3,5)}.",
    ),
  },
  {
    id: "param-2d-mod",
    kicker: "Proof step 1 · Reduce modulo p₂",
    title: "Write y=5n+j and subtract n copies of p",
    description:
      "For a general lattice point (x,y)∈F, write y=np₂+j with 0≤j<p₂. Subtracting np moves the point to the residue layer j.",
    formula: "y=5n+j, 0≤j<5",
    insight: "This turns infinitely many layers into only five residue classes.",
    scene: base2D(
      [
        point2D([8, 7], "x=(8,7)", "optimum"),
        line2D([8, 7], [5, 2], "−p", C.rose),
        point2D([5, 2], "residue layer j=2", "integer"),
        point2D([2, 2], "h₂=(2,2)", "optimum"),
      ],
      "Example: 7=1·5+2, so subtracting p lands on layer j=2.",
    ),
  },
  {
    id: "param-2d-decompose",
    kicker: "Proof step 2 · Use e₁ for the remaining slack",
    title: "After rounding, the remaining horizontal distance is integral",
    description:
      "Cone membership gives x≥yp₁/p₂. Since x is integral, x=np₁+⌈jp₁/p₂⌉+i for some i∈ℤ₊. Hence every lattice point is generated by H.",
    formula: "(x,y)=i(1,0)+np+(⌈jp₁/p₂⌉,j)",
    insight: "For (8,7), the decomposition is (8,7)=3(1,0)+(3,5)+(2,2).",
    scene: base2D(
      [
        point2D([2, 2], "h₂", "optimum"),
        line2D([2, 2], [5, 2], "+3e₁", C.orange),
        line2D([5, 2], [8, 7], "+p", C.aqua),
        point2D([8, 7], "(8,7)", "optimum"),
      ],
      "Residue representative + horizontal slack + copies of p.",
    ),
  },
  {
    id: "param-2d-basis",
    kicker: "Generating set versus integral basis",
    title: "The ceiling set H need not already be minimal",
    description:
      "The notes explicitly say that identifying the integral basis inside H is nontrivial. For p=(3,5), (2,2)=2(1,1) and (3,4)=(1,1)+(2,3), so those two points are redundant.",
    formula: "B={(1,0),(1,1),(2,3),(3,5)}",
    insight: "Thus the formula on the slide constructs an integral generating set; the integral basis is a smaller subset in this example.",
    scene: base2D(
      [
        ...H2.map((h) => point2D(h, undefined, "integer")),
        ...B2.map((h, i) => point2D(h, i === 0 ? "integral basis" : undefined, "optimum")),
        line2D([1, 1], [2, 2], "2(1,1)", C.rose),
        line2D([1, 1], [3, 4], "+(2,3)", C.rose),
      ],
      "Highlighted points are the integral basis; the two remaining H-points are decomposable.",
    ),
  },
];

// Natural 3D analogue: C=cone(e1,e2,p), p=(2,3,5).
// This extension is not stated separately in the notes, but the same proof works coordinatewise.
const E1: Point3D = [1, 0, 0];
const E2: Point3D = [0, 1, 0];
const P3: Point3D = [2, 3, 5];
const H3: Point3D[] = [[1, 1, 1], [1, 2, 2], [2, 2, 3], [2, 3, 4], [2, 3, 5]];

function scale3(t: number, v: Point3D): Point3D {
  return [t * v[0], t * v[1], t * v[2]];
}

function coneMesh3D(scale: number): Mesh3D {
  return {
    id: `param-cone-${scale}`,
    vertices: [[0, 0, 0], scale3(scale, E1), scale3(scale, E2), scale3(scale, P3)],
    faces: [[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]],
    label: "truncated cone C",
    color: C.lime,
    edgeColor: C.muted,
    opacity: 0.17,
    style: "ghost",
  };
}

function coneCoordinates3D(q: Point3D): [number, number, number] {
  const l3 = q[2] / 5;
  return [q[0] - 2 * l3, q[1] - 3 * l3, l3];
}

function lattice3D(scale: number): Marker3D[] {
  const result: Marker3D[] = [];
  for (let x = 0; x <= 6; x += 1) {
    for (let y = 0; y <= 8; y += 1) {
      for (let z = 0; z <= 10; z += 1) {
        const q: Point3D = [x, y, z];
        const [l1, l2, l3] = coneCoordinates3D(q);
        if (l1 < -1e-9 || l2 < -1e-9 || l3 < -1e-9 || l1 + l2 + l3 > scale + 1e-9) continue;
        result.push(marker3D(`param-lattice-${x}-${y}-${z}`, q, undefined, "integer", 0.038));
      }
    }
  }
  return result;
}

const bounds3D: Scene3D["bounds"] = { x: [-0.4, 6.2], y: [-0.4, 8.2], z: [-0.4, 10.6] };

function base3D(
  extraMarkers: Marker3D[] = [],
  extraSegments: Segment3D[] = [],
  caption: { primary: string; secondary: string } = {
    primary: "Natural 3D analogue",
    secondary: "C=cone(e₁,e₂,(2,3,5)).",
  },
) {
  return scene3D({
    bounds: bounds3D,
    axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
    camera: { yaw: 0.82, pitch: 0.48, distance: 12.0 },
    verticalScale: 0.62,
    meshes: [coneMesh3D(2)],
    markers: [...lattice3D(2), ...extraMarkers],
    segments: [
      segment3D("param-e1", [0, 0, 0], scale3(3.5, E1), "e₁", C.orange),
      segment3D("param-e2", [0, 0, 0], scale3(3.5, E2), "e₂", C.aqua),
      segment3D("param-p", [0, 0, 0], P3, "p=(2,3,5)", C.violet),
      ...extraSegments,
    ],
    showAxes: true,
    showGround: true,
    showIntegerLattice: false,
    caption,
  });
}

const stages3D: VisualizationStage[] = [
  {
    id: "param-3d-cone",
    kicker: "3D analogue · Same geometry one dimension higher",
    title: "At fixed x₃, the cone cross-section is a translated nonnegative quadrant",
    description:
      "For C=cone(e₁,e₂,(2,3,5)), an integer point satisfies x₁≥2x₃/5 and x₂≥3x₃/5. The two coordinate rays provide independent slack inside each horizontal layer.",
    formula: "F=C∩ℤ³, C=cone(e₁,e₂,(2,3,5))",
    insight: "The 2D horizontal ray becomes a 3D horizontal quadrant.",
    scene: base3D(),
  },
  {
    id: "param-3d-H",
    kicker: "3D ceiling construction",
    title: "Round both boundary coordinates upward on each residue layer",
    description:
      "For j=1,…,5, h_j=(⌈2j/5⌉,⌈3j/5⌉,j) is the componentwise-minimal lattice point on layer x₃=j. Every other lattice point on that layer is obtained by adding k₁e₁+k₂e₂.",
    formula: "H={e₁,e₂}∪{(⌈2j/5⌉,⌈3j/5⌉,j):j=1,…,5}",
    insight: "One leftmost point in 2D becomes one lower-left corner in 3D.",
    scene: base3D(
      H3.map((h, i) => marker3D(`param-h-${i}`, h, `h${i + 1}`, "optimum", 0.085)),
      H3.flatMap((h, i): Segment3D[] => [
        segment3D(`param-hx-${i}`, h, [h[0] + 1.7, h[1], h[2]], "+ℤ₊e₁", C.orange, { width: 2 }),
        segment3D(`param-hy-${i}`, h, [h[0], h[1] + 1.7, h[2]], "+ℤ₊e₂", C.aqua, { width: 2 }),
      ]),
      {
        primary: "Five residue-layer corners",
        secondary: "Each h_j anchors the integer quadrant on x₃=j.",
      },
    ),
  },
  {
    id: "param-3d-mod",
    kicker: "3D proof step 1 · Reduce modulo p₃",
    title: "Write x₃=5n+j and subtract np",
    description:
      "Exactly as in 2D, only the last coordinate controls the residue class. For x=(5,6,7), subtracting p=(2,3,5) leaves (3,3,2) on layer j=2.",
    formula: "7=1·5+2,  (5,6,7)-p=(3,3,2)",
    insight: "The modular part of the proof is unchanged.",
    scene: base3D(
      [
        marker3D("param-x", [5, 6, 7], "x=(5,6,7)", "optimum", 0.1),
        marker3D("param-r", [3, 3, 2], "x-p", "integer", 0.08),
        marker3D("param-h2", [1, 2, 2], "h₂", "optimum", 0.09),
      ],
      [segment3D("param-minus-p", [5, 6, 7], [3, 3, 2], "−p", C.rose, { dashed: true })],
      {
        primary: "Reduce the third coordinate modulo five",
        secondary: "The target is moved to residue layer j=2.",
      },
    ),
  },
  {
    id: "param-3d-decompose",
    kicker: "3D proof step 2 · Coordinate slack",
    title: "The residual displacement is generated by e₁ and e₂",
    description:
      "On layer j=2, (3,3,2)-h₂=(2,1,0)=2e₁+e₂. Adding back p gives a complete nonnegative integral decomposition of x.",
    formula: "(5,6,7)=2e₁+e₂+p+h₂",
    insight: "This is precisely the coordinatewise extension of the 2D proof.",
    scene: base3D(
      [
        marker3D("param-d0", [1, 2, 2], "h₂", "optimum", 0.09),
        marker3D("param-d1", [3, 2, 2], undefined, "integer", 0.07),
        marker3D("param-d2", [3, 3, 2], undefined, "integer", 0.07),
        marker3D("param-d3", [5, 6, 7], "x", "optimum", 0.1),
      ],
      [
        segment3D("param-step1", [1, 2, 2], [3, 2, 2], "+2e₁", C.orange),
        segment3D("param-step2", [3, 2, 2], [3, 3, 2], "+e₂", C.aqua),
        segment3D("param-step3", [3, 3, 2], [5, 6, 7], "+p", C.violet),
      ],
      {
        primary: "Explicit integral decomposition",
        secondary: "All coefficients are nonnegative integers.",
      },
    ),
  },
  {
    id: "param-3d-general",
    kicker: "General n-dimensional pattern",
    title: "The same residue-and-ceiling proof works for cone(e₁,…,eₙ₋₁,p)",
    description:
      "This higher-dimensional extension is not stated separately in the notes, but it follows by the identical calculation: reduce x_n modulo p_n and round the first n−1 boundary coordinates componentwise.",
    formula: "H={e₁,…,eₙ₋₁}∪{(⌈jp₁/pₙ⌉,…,⌈jpₙ₋₁/pₙ⌉,j):j=1,…,pₙ}",
    insight: "Finite generation generalizes cleanly; deciding which elements are actually needed in the integral basis remains a separate minimality problem.",
    scene: base3D(
      H3.map((h, i) => marker3D(`param-general-${i}`, h, i === 0 ? "residue representatives" : undefined, "optimum", 0.08)),
      [],
      {
        primary: "Higher-dimensional residue template",
        secondary: "One rounded corner per residue class, plus the first n−1 coordinate rays.",
      },
    ),
  },
];

const examples: VisualizationExample[] = [
  {
    id: "parametric-2d",
    title: "2D · p=(3,5) from the notes",
    description: "Exact ceiling construction, full proof, and the resulting integral basis.",
    stages: stages2D,
  },
  {
    id: "parametric-3d",
    title: "3D · p=(2,3,5) analogue",
    description: "The same residue proof with a two-dimensional slack quadrant in every layer.",
    stages: stages3D,
  },
];

const visualization: VisualizationDefinition = {
  id: "parametric-integral-generating-set",
  title: "Parametric Integral Generating Set — Ceiling Rounding by Residue Class",
  shortTitle: "Parametric generating set",
  chapter: "Integral generating sets",
  order: 0,
  description:
    "Visualizes the parametric feasible set from Chapter 21, explains why the ceiling formula gives a finite integral generating set, distinguishes it from the integral basis, and shows the same mechanism in three dimensions.",
  difficulty: "Intermediate",
  duration: 16,
  accent: C.aqua,
  visualLabel: "Residue-layer geometry",
  insightLabel: "Why the formula works",
  controls: { grid: true, lattice: true, vertices: false, labels: true },
  stages: stages2D,
  examples,
  proof: {
    title: "Residue-and-ceiling proof",
    steps: [
      "Write y=np₂+j with 0≤j<p₂.",
      "From cone membership, x≥yp₁/p₂=np₁+jp₁/p₂. Since x is integral, x=np₁+⌈jp₁/p₂⌉+i for some i∈ℤ₊.",
      "Hence (x,y)=i(1,0)+np+(⌈jp₁/p₂⌉,j), proving that H generates F integrally.",
      "For p=(3,5), the generating set H has six points, while its integral basis is {(1,0),(1,1),(2,3),(3,5)}.",
      "For cone(e₁,…,eₙ₋₁,p), the same argument works coordinatewise and gives the displayed n-dimensional generating-set formula.",
    ],
  },
};

export default visualization;
