import type {
  Point2D,
  PolygonPrimitive,
  Primitive,
  Scene,
} from "@/engine/types";
import {
  add,
  basisVectors,
  latticePoints,
  latticeScene,
  LATTICE_COLORS,
  scale,
} from "@/visualizations/helpers/lattice-scenes";
import type { Basis2D } from "@/visualizations/helpers/lattice-scenes";
import type { VisualizationDefinition } from "@/visualizations/types";

const basis: Basis2D = [
  [3, 1],
  [1, 3],
];
const viewport: Scene["viewport"] = { x: [-7, 7], y: [-6, 6] };
const origin: Point2D = [0, 0];
const x: Point2D = [1.55, 0.65];
const y: Point2D = [-1.45, -0.35];
const negativeY: Point2D = [1.45, 0.35];
const halfDifference: Point2D = [1.5, 0.5];
const witness: Point2D = [3, 1];

const latticeBackground = () => latticePoints(basis, viewport, 8);

function diamond(
  radius: number,
  label: string,
  style: PolygonPrimitive["style"] = "feasible",
  fromRadius?: number,
): PolygonPrimitive {
  return {
    kind: "polygon",
    points: [
      [radius, 0],
      [0, radius],
      [-radius, 0],
      [0, -radius],
    ],
    fromPoints: fromRadius
      ? [
          [fromRadius, 0],
          [0, fromRadius],
          [-fromRadius, 0],
          [0, -fromRadius],
        ]
      : undefined,
    label,
    style,
  };
}

function translatedCell(first: number, second: number): PolygonPrimitive {
  const shift = add(scale(first, basis[0]), scale(second, basis[1]));
  return {
    kind: "polygon",
    points: [
      shift,
      add(shift, basis[0]),
      add(add(shift, basis[0]), basis[1]),
      add(shift, basis[1]),
    ],
    style: "component",
  };
}

const centeredThresholdCell: PolygonPrimitive = {
  kind: "polygon",
  points: [
    add(basis[0], basis[1]),
    add(basis[0], scale(-1, basis[1])),
    scale(-1, add(basis[0], basis[1])),
    add(scale(-1, basis[0]), basis[1]),
  ],
  label: "open body · area 32",
  style: "removed",
};

const scene = (
  primitives: Primitive[],
  caption: Scene["caption"],
  overrides: Partial<Scene> = {},
): Scene =>
  latticeScene(basis, {
    viewport,
    primitives,
    caption,
    ...overrides,
  });

const visualization: VisualizationDefinition = {
  id: "minkowski-convex-body-theorem",
  title: "Minkowski’s Convex Body Theorem",
  shortTitle: "Minkowski’s theorem",
  chapter: "Lattice theory",
  order: 3,
  description:
    "Turn volume into a nonzero lattice point by halving a symmetric convex body, folding it into one fundamental cell, and converting a collision into a lattice difference.",
  difficulty: "Intermediate",
  duration: 16,
  accent: LATTICE_COLORS.rose,
  visualLabel: "Convex body proof",
  insightLabel: "Geometry-of-numbers insight",
  controls: {
    constraints: false,
    lattice: false,
    vertices: false,
    labels: true,
  },
  stages: [
    {
      id: "setup",
      kicker: "01 · Geometry of numbers",
      title: "A continuous body is forced to meet a discrete lattice",
      description:
        "The lattice generated by b₁=(3,1) and b₂=(1,3) has determinant 8. The centrally symmetric diamond K has radius 5 and area 50.",
      formula: "det(L)=|det B|=8   ·   area(K)=2·5²=50",
      insight:
        "Minkowski’s theorem compares only the body’s volume with the lattice’s fundamental volume; it does not need to inspect all lattice points individually.",
      scene: scene(
        [
          ...latticeBackground(),
          diamond(5, "K · area 50"),
          ...basisVectors(basis),
        ],
        { label: "Lattice and convex body", detail: "det(L)=8 · area(K)=50" },
      ),
    },
    {
      id: "theorem",
      kicker: "02 · Minkowski’s theorem",
      title: "More than 2ⁿ fundamental volumes force a nonzero lattice point",
      description:
        "Let L be a full-rank lattice in ℝⁿ and let K be measurable, convex, and centrally symmetric. If its volume exceeds the threshold, K contains a nonzero lattice point.",
      formula: "K=−K, K convex, vol(K)>2ⁿdet(L)   ⇒   (K∩L)∖{0}≠∅",
      insight:
        "In two dimensions the factor is 2²=4, so our threshold is 4·8=32 and the body’s area 50 is safely above it.",
      scene: scene(
        [...latticeBackground(), diamond(5, "K=−K"), { kind: "point", at: origin, label: "center 0", style: "optimum" }],
        { label: "Minkowski threshold", detail: "50>2²·8=32" },
      ),
    },
    {
      id: "volume-threshold",
      kicker: "03 · Why the factor 2ⁿ?",
      title: "Halving all coordinates divides volume by 2ⁿ",
      description:
        "Scale K by one half. In dimension n, this multiplies volume by (1/2)ⁿ. The theorem’s assumption becomes exactly the volume condition in Blichfeldt’s lemma.",
      formula: "vol(½K)=vol(K)/2ⁿ > det(L)",
      insight:
        "For this diamond, area(½K)=50/4=12.5, which is larger than the area 8 of one fundamental lattice cell.",
      scene: scene(
        [
          ...latticeBackground(),
          diamond(5, "K", "feasible"),
          diamond(2.5, "½K · area 12.5", "component", 5),
        ],
        { label: "Scale by one half", detail: "area drops by 2²=4" },
      ),
    },
    {
      id: "fundamental-tiling",
      kicker: "04 · Fundamental cells",
      title: "The lattice tiles space with area-8 cells",
      description:
        "Translate one fundamental parallelogram by every lattice vector. These cells cover the plane with disjoint interiors and each has volume det(L).",
      formula: "ℝ²=⋃_{ℓ∈L}(𝒫(B)+ℓ)   ·   area(𝒫(B))=det(L)=8",
      insight:
        "Reducing a point modulo L means translating it into one chosen fundamental cell without changing its residue class.",
      scene: scene(
        [
          ...latticeBackground(),
          ...[-1, 0, 1].flatMap((first) =>
            [-1, 0, 1].map((second) => translatedCell(first, second)),
          ),
          diamond(2.5, "½K", "integer-hull"),
        ],
        { label: "Fundamental tiling", detail: "each cell has area 8" },
      ),
    },
    {
      id: "fold-modulo-lattice",
      kicker: "05 · Fold modulo L",
      title: "A set larger than one cell must overlap itself after folding",
      description:
        "Translate every piece of ½K into the reference cell. Since its total area is 12.5 but the cell has area only 8, two distinct original points must land at the same position.",
      formula: "area(½K)>det(L)   ⇒   ∃x≠y∈½K with x≡y (mod L)",
      insight:
        "This is Blichfeldt’s lemma: continuous volume becomes a pigeonhole principle on one fundamental domain.",
      scene: scene(
        [
          ...latticeBackground(),
          translatedCell(0, 0),
          diamond(2.5, "½K", "integer-hull"),
          { kind: "point", at: x, label: "x", style: "optimum" },
          { kind: "point", at: y, label: "y", style: "fractional" },
          { kind: "vector", from: y, to: x, label: "+b₁ · fold to same residue", color: LATTICE_COLORS.rose, animate: true },
        ],
        { label: "Modulo-lattice folding", detail: "y+b₁=x in the reference cell" },
      ),
    },
    {
      id: "blichfeldt-collision",
      kicker: "06 · Collision",
      title: "Equal residues produce a nonzero lattice difference",
      description:
        "Choose x=(1.55,0.65) and y=(−1.45,−0.35) inside ½K. They fold to the same residue because their difference is exactly b₁.",
      formula: "x−y=(3,1)=b₁∈L∖{0}",
      insight:
        "The two points are distinct, so the lattice difference cannot be zero. It remains only to prove that this difference lies inside K.",
      scene: scene(
        [
          ...latticeBackground(),
          diamond(2.5, "½K", "integer-hull"),
          { kind: "point", at: x, label: "x", style: "optimum" },
          { kind: "point", at: y, label: "y", style: "fractional" },
          { kind: "vector", from: y, to: x, label: "x−y=b₁", color: LATTICE_COLORS.rose, animate: true },
        ],
        { label: "Blichfeldt pair", detail: "distinct points · lattice difference" },
      ),
    },
    {
      id: "symmetry-convexity",
      kicker: "07 · Use both hypotheses",
      title: "Symmetry reflects −y; convexity keeps the midpoint",
      description:
        "Because ½K is centrally symmetric, −y also lies in ½K. Convexity puts the midpoint of x and −y in ½K. Doubling that midpoint returns to K.",
      formula: "x,−y∈½K   ⇒   (x−y)/2∈½K   ⇒   x−y∈K",
      insight:
        "Equivalently, central symmetry and convexity give the set inclusion ½K−½K⊆K.",
      scene: scene(
        [
          ...latticeBackground(),
          diamond(2.5, "½K", "integer-hull"),
          diamond(5, "K", "feasible", 2.5),
          { kind: "point", at: x, label: "x", style: "optimum" },
          { kind: "point", at: negativeY, label: "−y", style: "fractional", animateFrom: y },
          { kind: "point", at: halfDifference, label: "(x−y)/2", style: "integer" },
          { kind: "vector", from: origin, to: witness, label: "double → x−y", color: LATTICE_COLORS.rose, animate: true },
        ],
        { label: "Symmetry plus convexity", detail: "½K−½K⊆K" },
      ),
    },
    {
      id: "lattice-witness",
      kicker: "08 · The promised point",
      title: "The body contains the nonzero lattice vector b₁",
      description:
        "The collision created b₁=(3,1), and the symmetry-convexity step placed it inside K. This is the theorem’s required witness.",
      formula: "b₁=(3,1)∈K∩L and b₁≠0",
      insight:
        "The proof guarantees some nonzero lattice point; the animation exposes a concrete one for this lattice and body.",
      scene: scene(
        [
          ...latticeBackground(),
          diamond(5, "K · area 50"),
          { kind: "vector", from: origin, to: witness, label: "b₁∈K∩L", color: LATTICE_COLORS.rose, animate: true },
          { kind: "point", at: witness, label: "nonzero witness", style: "integer" },
        ],
        { label: "Minkowski witness", detail: "nonzero lattice point inside K" },
      ),
    },
    {
      id: "short-vector-corollary",
      kicker: "09 · Short-vector corollary",
      title: "Apply the theorem to a Euclidean ball",
      description:
        "A radius-r ball is convex and centrally symmetric. Once its volume exceeds 2ⁿdet(L), it contains a nonzero lattice vector, giving an upper bound on the shortest-vector length.",
      formula: "λ₁(L)≤2(det(L)/vol(B₂ⁿ))¹⁄ⁿ   ·   in ℝ²: λ₁(L)≤√(4det(L)/π)",
      insight:
        "For det(L)=8 the bound is √(32/π)≈3.19; our vector b₁ has length √10≈3.16 and fits inside that radius.",
      scene: scene(
        [
          ...latticeBackground(),
          { kind: "circle", at: origin, radius: Math.sqrt(32 / Math.PI) + 0.05, label: "Euclidean ball", style: "component", color: LATTICE_COLORS.violet, animate: true },
          { kind: "vector", from: origin, to: witness, label: "‖b₁‖=√10", color: LATTICE_COLORS.rose, animate: true },
          { kind: "point", at: witness, style: "integer" },
        ],
        { label: "Shortest-vector bound", detail: "ball volume crosses 2²det(L)" },
      ),
    },
    {
      id: "strict-threshold",
      kicker: "10 · Why strict inequality?",
      title: "At exactly 2ⁿdet(L), an open body can still miss every nonzero point",
      description:
        "The open centered parallelogram with coefficients |α₁|<1 and |α₂|<1 has area exactly 4det(L)=32. Its nonzero lattice points lie on the excluded boundary.",
      formula: "K₀={α₁b₁+α₂b₂:|α₁|,|α₂|<1}   ·   area(K₀)=32",
      insight:
        "The strict volume assumption avoids this boundary case. Stronger closed-body versions can replace > by ≥ with additional hypotheses.",
      scene: scene(
        [
          ...latticeBackground(),
          centeredThresholdCell,
          ...basisVectors(basis, ["boundary b₁", "boundary b₂"], [LATTICE_COLORS.rose, LATTICE_COLORS.rose]),
        ],
        { label: "Threshold example", detail: "open interior contains only the origin" },
      ),
    },
    {
      id: "proof-chain",
      kicker: "11 · Proof in one chain",
      title: "Volume → collision → difference → lattice witness",
      description:
        "Every part of the argument has a distinct job: scaling reaches the fundamental-volume threshold, Blichfeldt creates the pair, and symmetry plus convexity returns its difference to K.",
      formula: "vol(K)>2ⁿdet(L) ⇒ vol(½K)>det(L) ⇒ x−y∈L∖{0} ⇒ x−y∈K",
      insight:
        "That single chain is Minkowski’s bridge between continuous convex geometry and discrete lattice structure.",
      scene: scene(
        [
          ...latticeBackground(),
          diamond(5, "K"),
          diamond(2.5, "½K", "integer-hull"),
          { kind: "point", at: x, label: "x", style: "optimum" },
          { kind: "point", at: y, label: "y", style: "fractional" },
          { kind: "vector", from: y, to: x, label: "x−y=b₁∈K∩L", color: LATTICE_COLORS.rose, animate: true },
        ],
        { label: "Complete proof mechanism", detail: "continuous volume produces a discrete point" },
      ),
    },
  ],
  proof: {
    title: "Why does the halving-and-folding proof work?",
    steps: [
      "Scale the body to A=½K. Since volume scales by (1/2)ⁿ, the hypothesis gives vol(A)>det(L).",
      "Fold A modulo L into one fundamental domain of volume det(L). By Blichfeldt’s lemma, two distinct points x,y∈A have the same residue, so x−y∈L∖{0}.",
      "Central symmetry of K implies symmetry of A, hence −y∈A whenever y∈A.",
      "Convexity of A implies that the midpoint (x+(−y))/2=(x−y)/2 belongs to A=½K.",
      "Multiplying by two yields x−y∈K. Together with the collision, x−y is a nonzero lattice point in K.",
      "The factor 2ⁿ appears only because the proof first halves K in every coordinate before applying the fundamental-volume pigeonhole principle.",
    ],
  },
};

export default visualization;
