import type { Point2D, Primitive } from "@/engine/types";
import type { VisualizationDefinition, VisualizationExample, VisualizationStage } from "@/visualizations/types";
import {
  PROXIMITY_COLORS as C,
  label2D,
  line2D,
  point2D,
  scene2D,
} from "@/visualizations/helpers/standard-form-proximity-scenes";

function representable(limit: number, generators: number[]): Set<number> {
  const hit = new Set<number>([0]);
  for (let s = 0; s <= limit; s += 1) {
    if (!hit.has(s)) continue;
    for (const a of generators) if (s + a <= limit) hit.add(s + a);
  }
  return hit;
}

function numberLine(generators: number[], limit: number, extra: Primitive[], secondary: string) {
  const hit = representable(limit, generators);
  return scene2D(
    [
      line2D([0,0],[limit,0], "b", C.muted, "constraint"),
      ...Array.from({ length: limit + 1 }, (_, b) =>
        point2D([b,0], b % 5 === 0 ? `${b}` : undefined, hit.has(b) ? "integer" : "fractional"),
      ),
      ...extra,
    ],
    { primary: `Frobenius semigroup generated by ${generators.join(", ")}`, secondary },
    { viewport: { x: [-1,limit+1], y: [-1.4,3.0] }, showGrid: false, showLattice: false, axisLabels: { x: "right-hand side b", y: "" }, scaleMode: "stretch" },
  );
}

function pairStages(a: number, b: number, extraGenerator?: number): VisualizationStage[] {
  const generators = extraGenerator ? [a,b,extraGenerator] : [a,b];
  const delta = Math.max(...generators);
  const guaranteed = (a - 1) * b;
  const theoremBound = delta * (delta - 1);
  const residues = Array.from({ length: a }, (_, m) => ({ m, residue: (m*b) % a }));

  return [
    {
      id: `frob-${generators.join("-")}-definition`,
      kicker: "Chapter 25 · Frobenius problem",
      title: "Which large right-hand sides are nonnegative integer combinations?",
      description:
        `For generators ${generators.join(", ")}, a right-hand side is representable when b=Σ a_i x_i with x_i∈ℤ₊. The Frobenius threshold is the first point beyond which every integer is representable.`,
      formula: "b=Σᵢ aᵢxᵢ,   x∈ℤ₊ⁿ",
      insight: "The Chapter-25 application uses a coprime pair among the generators; any additional generators can only make representation easier.",
      scene: numberLine(generators, 26, [label2D([1,2.1], "filled = representable · open/red = hole", "accent")], "The holes occur near the origin; eventually the semigroup has no gaps."),
    },
    {
      id: `frob-${generators.join("-")}-residues`,
      kicker: "Example 153 · Residue classes",
      title: `Multiples of ${b} visit every residue class modulo ${a}`,
      description:
        `Because gcd(${a},${b})=1, the residues of m·${b} modulo ${a}, for m=0,…,${a-1}, are all distinct and hence equal to every class 0,…,${a-1}.`,
      formula: `m·${b}=q_m·${a}+r_m,   {r_m:m=0,…,${a-1}}={0,…,${a-1}}`,
      insight: "This finite residue table is the entire arithmetic engine of the proof.",
      scene: scene2D(
        [
          ...residues.map(({m,residue},i) => point2D([m,residue], `${m}·${b}≡${residue}`, "integer")),
          label2D([0.2,a+0.4], `all ${a} residues appear once`, "accent"),
        ],
        { primary: `${b} modulo ${a}`, secondary: residues.map(r => `${r.m}→${r.residue}`).join(" · ") },
        { viewport: { x: [-0.7,a], y: [-0.7,a+1.2] }, axisLabels: { x: "m", y: `m·${b} mod ${a}` }, showLattice: true },
      ),
    },
    {
      id: `frob-${generators.join("-")}-construction`,
      kicker: "Example 153 · Construct a representation",
      title: "Choose the multiple with the correct residue and fill the rest with the smaller generator",
      description:
        `For any N≥(${a}−1)·${b}=${guaranteed}, choose m∈{0,…,${a-1}} with m·${b}≡N (mod ${a}). Then N−m·${b}≥0 and is divisible by ${a}, so N=((N−m·${b})/${a})·${a}+m·${b}.`,
      formula: `N≥(a−1)b ⇒ N=q·a+m·b with q,m∈ℤ₊`,
      insight: "This is the residue-class construction in a sign-transparent form: choose m first, then the remaining coefficient is automatically nonnegative and integral.",
      scene: numberLine(generators, 26, [
        point2D([23,0], "N=23=2·4+3·5", "optimum"),
        label2D([12,2.1], "for 4,5: pick m=3 because 15≡23 mod 4", "accent"),
      ], "Example N=23: the residue chooses three copies of 5, then two copies of 4."),
    },
    {
      id: `frob-${generators.join("-")}-bound`,
      kicker: "Example 153 · Bound",
      title: "The residue construction implies the stated Δ(Δ−1) upper bound",
      description:
        `The construction works from (a−1)b=${guaranteed} onward. Since a<b≤Δ and a−1≤Δ−1, (a−1)b≤Δ(Δ−1)=${theoremBound}. Therefore the Frobenius threshold is at most Δ(Δ−1).`,
      formula: "t≤(a_i−1)a_j≤Δ(Δ−1)",
      insight: extraGenerator
        ? `The third generator ${extraGenerator} only adds more representable values, so the same coprime-pair bound remains valid.`
        : "The bound is deliberately simple rather than exact; for two coprime generators the classical exact conductor can be smaller.",
      scene: numberLine(generators, 26, [
        line2D([guaranteed,1.0],[26,1.0], `guaranteed tail from ${guaranteed}`, C.aqua),
        line2D([theoremBound,1.65],[26,1.65], `coarser Δ(Δ−1)=${theoremBound}`, C.orange),
      ], "A proof threshold need not equal the exact Frobenius conductor."),
    },
  ];
}

const stages = pairStages(4,5);
const examples: VisualizationExample[] = [
  { id: "frob-4-5", title: "Two generators · 4 and 5", stages },
  { id: "frob-4-5-7", title: "Three generators · 4, 5, 7", stages: pairStages(4,5,7) },
];

const visualization: VisualizationDefinition = {
  id: "frobenius-example-153",
  title: "Example 153 — Frobenius Numbers via Residue Classes",
  shortTitle: "Frobenius residues · Example 153",
  chapter: "Standard-form proximity",
  order: 4,
  description:
    "Visualizes the Frobenius application in Chapter 25: representable right-hand sides, the permutation of residue classes produced by a coprime pair, the constructive representation of every sufficiently large integer, and the Δ(Δ−1) bound.",
  difficulty: "Intermediate",
  duration: 12,
  accent: C.lime,
  visualLabel: "Semigroup and residues",
  insightLabel: "Number-theoretic consequence",
  controls: { grid: true, lattice: true, vertices: false, labels: true },
  stages,
  examples,
  proof: {
    title: "Residue proof of Example 153",
    steps: [
      "Choose a coprime pair a_i<a_j. Multiplication by a_j permutes the residue classes modulo a_i.",
      "For any N≥(a_i−1)a_j, choose m∈{0,…,a_i−1} with m a_j≡N (mod a_i).",
      "Then N−m a_j≥0 and is divisible by a_i, so N=q a_i+m a_j for q∈ℤ₊.",
      "Thus every N≥(a_i−1)a_j is representable. Since (a_i−1)a_j≤Δ(Δ−1), the stated bound follows.",
    ],
  },
};

export default visualization;
