import type { Primitive } from "@/engine/types";
import type {
  VisualizationDefinition,
  VisualizationExample,
  VisualizationStage,
} from "@/visualizations/types";
import {
  TDI_COLORS,
  marker3D,
  point2D,
  prismVertices,
  scene2D,
  scene3D,
  segment3D,
  triangle2DConstraints,
  triangle2DTdiConstraints,
  triangle2DVertexMarkers,
  trianglePrismMesh,
  vector2D,
} from "@/visualizations/helpers/tdi-scenes";

const apexNormalsOriginal: Array<[number, number]> = [[-2,1],[2,1]];
const apexNormalsHilbert: Array<[number, number]> = [[-2,1],[-1,1],[0,1],[1,1],[2,1]];

const stages2D: VisualizationStage[] = [
  {
    id: "tdi-construct-2d-start",
    kicker: "Chapter 23 · Theorem 141 · 2D",
    title: "Start from any nonredundant rational description",
    description:
      "For P=conv{(0,0),(1,2),(2,0)}, begin with its three facet inequalities −x₂≤0, −2x₁+x₂≤0, and 2x₁+x₂≤4. This description is geometrically exact but is not TDI.",
    formula: "P={x:Cx≤d}",
    insight:
      "Theorem 141 does not claim that every description of P is TDI. It constructs a new one, potentially with redundant inequalities.",
    scene: scene2D(
      triangle2DConstraints,
      triangle2DVertexMarkers(),
      {
        viewport: { x: [-0.8, 2.8], y: [-0.8, 2.9] },
        caption: {
          primary: "Nonredundant triangle description",
          secondary: "Correct polytope, but the apex normal cone is not integrally generated by its two facet normals.",
        },
      },
    ),
  },
  {
    id: "tdi-construct-2d-hilbert",
    kicker: "Theorem 141 · Minimal-face normal cone",
    title: "Compute an integral generating set for each minimal-face cone",
    description:
      "At the apex, the two facet normals (−2,1) and (2,1) generate a cone containing the additional primitive integer directions (−1,1),(0,1),(1,1). These are inserted into the row set.",
    formula: "H_apex={(−2,1),(−1,1),(0,1),(1,1),(2,1)}",
    insight:
      "This is exactly the construction stated in Theorem 141: replace each minimal-face normal cone by an integral generating set.",
    scene: scene2D(
      triangle2DConstraints,
      [
        point2D([1,2], "minimal face F={(1,2)}", "optimum"),
        ...apexNormalsOriginal.map<Primitive>((a, index) =>
          vector2D([1,2], [1+0.35*a[0],2+0.35*a[1]], index === 0 ? "original facet normals" : "", TDI_COLORS.orange),
        ),
        ...apexNormalsHilbert.slice(1,4).map<Primitive>((a, index) =>
          vector2D([1,2], [1+0.35*a[0],2+0.35*a[1]], index === 1 ? "missing integer normals" : "", TDI_COLORS.violet),
        ),
      ],
      {
        viewport: { x: [-0.8, 2.8], y: [-0.8, 3.4] },
        caption: {
          primary: "Complete the apex cone with its integer generators",
          secondary: "The arrows are translated normal vectors.",
        },
      },
    ),
  },
  {
    id: "tdi-construct-2d-rhs",
    kicker: "Theorem 141 · Equation (59)",
    title: "Turn every new normal a into the valid inequality aᵀx≤maxₚ aᵀx",
    description:
      "For the three new apex normals, the supporting right-hand sides are 1,2,3: −x₁+x₂≤1, x₂≤2, x₁+x₂≤3. The endpoint cones similarly contribute −x₁≤0 and x₁≤2.",
    formula: "b_k=max{a_kᵀx:x∈P}",
    insight:
      "Because each new row is supported at P, adding it does not change the polyhedron—it only strengthens the representation.",
    scene: scene2D(
      triangle2DTdiConstraints,
      [
        ...triangle2DVertexMarkers(),
        point2D([1,2], "−x₁+x₂=1, x₂=2, x₁+x₂=3", "optimum"),
      ],
      {
        viewport: { x: [-0.8, 2.8], y: [-0.8, 2.9] },
        caption: {
          primary: "Same P, richer inequality system",
          secondary: "The added inequalities are redundant geometrically but essential arithmetically.",
        },
      },
    ),
  },
  {
    id: "tdi-construct-2d-final",
    kicker: "Theorem 141 + Corollary 142",
    title: "The resulting system is TDI; here its right-hand side is integral as well",
    description:
      "Theorem 141 guarantees TDI after the face-cone construction. Since this triangle is integral, Corollary 142 says a TDI description can be chosen with both A and b integral; the displayed one has exactly that property.",
    formula: "P integral ⇔ ∃ integral A,b with Ax≤b TDI",
    insight:
      "TDI is a property of a representation, while integrality is a property of the polyhedron itself.",
    scene: scene2D(
      triangle2DTdiConstraints,
      triangle2DVertexMarkers(),
      {
        viewport: { x: [-0.8, 2.8], y: [-0.8, 2.9] },
        caption: {
          primary: "Integral TDI representation of an integral polytope",
          secondary: "Corollary 142 closes the equivalence.",
        },
      },
    ),
  },
];

const prismIntegerMarkers = prismVertices.map((at, index) =>
  marker3D(`prism-v-${index}`, at, index === 5 ? "top apex (1,2,1)" : undefined, index === 5 ? "optimum" : "integer", index === 5 ? 0.11 : 0.065),
);

const stages3D: VisualizationStage[] = [
  {
    id: "tdi-construct-3d-start",
    kicker: "Chapter 23 · Theorem 141 · 3D",
    title: "Use the triangular prism as a genuine three-dimensional test case",
    description:
      "Let P=conv{(0,0),(1,2),(2,0)}×[0,1]. Its nonredundant description consists of the three triangle facet inequalities together with 0≤x₃≤1.",
    formula: "P=T×[0,1]⊂ℝ³",
    insight:
      "This 3D example is an explicit illustration of the dimension-independent construction in Theorem 141.",
    scene: scene3D({
      bounds: { x: [-0.8, 2.8], y: [-0.8, 3.0], z: [-0.5, 2.0] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.78, pitch: 0.45, distance: 6.3 },
      meshes: [trianglePrismMesh("tdi-prism-start", "P=T×[0,1]")],
      markers: prismIntegerMarkers,
      caption: {
        primary: "Nonredundant 3D prism description",
        secondary: "The triangular cross-section carries the same arithmetic obstruction as the 2D apex.",
      },
    }),
  },
  {
    id: "tdi-construct-3d-normal-cone",
    kicker: "Theorem 141 · 3D minimal-face cone",
    title: "At the top apex, complete the horizontal part of the normal cone",
    description:
      "At v=(1,2,1), the original tight normals are (−2,1,0),(2,1,0),(0,0,1). The missing integer horizontal directions are (−1,1,0),(0,1,0),(1,1,0).",
    formula: "H_v={(-2,1,0),(-1,1,0),(0,1,0),(1,1,0),(2,1,0),(0,0,1)}",
    insight:
      "The vertical coordinate contributes the primitive generator e₃; the nontrivial completion happens in the triangle's normal plane.",
    scene: scene3D({
      bounds: { x: [-0.8, 3.5], y: [-0.8, 3.6], z: [-0.5, 2.5] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.78, pitch: 0.45, distance: 6.5 },
      meshes: [trianglePrismMesh("tdi-prism-ghost", "P", 0.08)],
      markers: [marker3D("prism-apex", [1,2,1], "v=(1,2,1)", "optimum", 0.11)],
      segments: [
        segment3D("n-left", [1,2,1], [0,2.5,1], "(−2,1,0)", TDI_COLORS.orange),
        segment3D("n-midleft", [1,2,1], [0.5,2.5,1], "(−1,1,0)", TDI_COLORS.violet),
        segment3D("n-mid", [1,2,1], [1,2.5,1], "(0,1,0)", TDI_COLORS.violet),
        segment3D("n-midright", [1,2,1], [1.5,2.5,1], "(1,1,0)", TDI_COLORS.violet),
        segment3D("n-right", [1,2,1], [2,2.5,1], "(2,1,0)", TDI_COLORS.orange),
        segment3D("n-up", [1,2,1], [1,2,2], "e₃", TDI_COLORS.aqua),
      ],
      caption: {
        primary: "Integral generating set of the 3D normal cone",
        secondary: "Translated to start at the top apex for visualization.",
      },
    }),
  },
  {
    id: "tdi-construct-3d-add-rows",
    kicker: "Theorem 141 · Add supported redundant inequalities",
    title: "Lift the 2D redundant inequalities through the prism",
    description:
      "Add −x₁≤0, −x₁+x₂≤1, x₂≤2, x₁+x₂≤3, and x₁≤2. They are independent of x₃, so each defines a vertical supporting plane of the same prism. Together with 0≤x₃≤1 they make every face-cone integrally generated.",
    formula: "b_k=max{a_kᵀx:x∈P} still leaves P unchanged",
    insight:
      "The construction is not about shrinking P. It is about enriching the list of valid supporting normals.",
    scene: scene3D({
      bounds: { x: [-0.8, 2.8], y: [-0.8, 3.0], z: [-0.5, 2.0] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.78, pitch: 0.45, distance: 6.3 },
      meshes: [trianglePrismMesh("tdi-prism-final", "same P with TDI description")],
      markers: prismIntegerMarkers,
      caption: {
        primary: "Same 3D polytope, TDI representation",
        secondary: "The extra vertical supporting planes are redundant in primal geometry.",
      },
    }),
  },
  {
    id: "tdi-construct-3d-corollary",
    kicker: "Corollary 142 · Integral polyhedron",
    title: "Because every prism vertex is integral, the TDI representation can use integral b",
    description:
      "All six prism vertices are integer. The lifted TDI inequalities have right-hand sides 0,1,2,3,4 together with x₃≤1 and −x₃≤0, so A and b are both integral.",
    formula: "P integral ⇔ P admits an integral TDI description",
    insight:
      "The prism makes Corollary 142 visible in three dimensions without changing the theorem's logic.",
    scene: scene3D({
      bounds: { x: [-0.8, 2.8], y: [-0.8, 3.0], z: [-0.5, 2.0] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.78, pitch: 0.45, distance: 6.3 },
      meshes: [trianglePrismMesh("tdi-prism-cor", "integral prism")],
      markers: prismIntegerMarkers,
      caption: {
        primary: "Integral TDI representation in 3D",
        secondary: "All minimal faces contain lattice points.",
      },
    }),
  },
];

const examples: VisualizationExample[] = [
  {
    id: "tdi-construction-2d",
    title: "2D · Triangle",
    description: "The exact triangle construction from Problem 12.1, organized as Theorem 141's algorithm.",
    stages: stages2D,
  },
  {
    id: "tdi-construction-3d",
    title: "3D · Triangular prism",
    description: "A three-dimensional extension illustrating the same minimal-face Hilbert-basis construction.",
    stages: stages3D,
  },
];

const visualization: VisualizationDefinition = {
  id: "tdi-representation-construction",
  title: "TDI IV — Constructing a TDI Description",
  shortTitle: "Construct a TDI system",
  chapter: "Total dual integrality",
  order: 4,
  description:
    "Theorem 141 and Corollary 142: every rational polyhedron has a TDI description, obtained from integral generating sets of minimal-face normal cones; integral polyhedra admit one with integral right-hand side.",
  difficulty: "Advanced",
  duration: 16,
  accent: TDI_COLORS.rose,
  controls: { constraints: true, grid: true, lattice: true, vertices: true, labels: true },
  stages: stages2D,
  examples,
  proof: {
    title: "Theorem 141 construction",
    steps: [
      "Start from a nonredundant rational description P={x:Cx≤d} with integral C.",
      "For every minimal face F_i, compute an integral generating set H_i of the cone generated by the rows tight on F_i.",
      "Use every vector a_k in the union of the H_i as a row of A and define b_k=max{a_kᵀx:x∈P}.",
      "These supported inequalities still describe exactly P.",
      "For any face F, its normal cone is a face of the minimal-face cones containing it, so the appropriate subset of H_i integrally generates that face cone; hence Ax≤b is TDI.",
    ],
  },
};

export default visualization;
