import type {
  VisualizationDefinition,
  VisualizationExample,
  VisualizationStage,
} from "@/visualizations/types";
import {
  TDI_COLORS,
  boxMesh,
  integerBoxMarkers,
  label2D,
  marker3D,
  point2D,
  scene2D,
  scene3D,
  segment3D,
  triangle2DTdiConstraints,
  triangle2DVertexMarkers,
  vector2D,
} from "@/visualizations/helpers/tdi-scenes";

const stages2D: VisualizationStage[] = [
  {
    id: "tdi-dual-2d-objective",
    kicker: "Chapter 23 · Theorem 139 · 2D",
    title: "An integral objective exposes one optimal face",
    description:
      "On the TDI triangle, maximize cᵀx for c=(3,2). The unique optimum is the apex x*=(1,2), where the inequalities x₁+x₂≤3 and 2x₁+x₂≤4 are both tight.",
    formula: "c=(3,2),   max{cᵀx:Ax≤b}=7 at x*=(1,2)",
    insight:
      "The objective c belongs to the cone generated by the normals of the constraints tight on its optimal face.",
    scene: scene2D(
      triangle2DTdiConstraints,
      [
        ...triangle2DVertexMarkers(),
        point2D([1, 2], "x*=(1,2)", "optimum"),
        vector2D([0, 0], [1.2, 0.8], "c=(3,2)", TDI_COLORS.rose),
      ],
      {
        viewport: { x: [-0.7, 2.8], y: [-0.7, 2.8] },
        objective: { vector: [3, 2], label: "c=(3,2)" },
        caption: {
          primary: "Integral objective and its optimal face",
          secondary: "The apex is the unique maximizing face.",
        },
      },
    ),
  },
  {
    id: "tdi-dual-2d-integral-representation",
    kicker: "Theorem 139 · TDI ⇒ integral dual optimum",
    title: "TDI turns the objective into an integer combination of tight normals",
    description:
      "At the apex, let a⁴=(1,1) correspond to x₁+x₂≤3 and a⁵=(2,1) to 2x₁+x₂≤4. Then c=a⁴+a⁵, so the dual multiplier vector with these two entries equal to one is integral.",
    formula: "c=(3,2)=(1,1)+(2,1),   y*∈ℤ₊ᵐ",
    insight:
      "This is the geometric content of an integral dual solution: its coordinates are integer multiplicities of active row vectors.",
    scene: scene2D(
      triangle2DTdiConstraints,
      [
        point2D([1, 2], "optimal face F", "optimum"),
        vector2D([1, 2], [1.55, 2.55], "a⁴=(1,1)", TDI_COLORS.aqua),
        vector2D([1, 2], [2.0, 2.5], "a⁵=(2,1)", TDI_COLORS.orange),
        label2D([0.1, 2.55], "c=a⁴+a⁵", "accent"),
      ],
      {
        viewport: { x: [-0.7, 3.0], y: [-0.7, 3.2] },
        caption: {
          primary: "Integral normal decomposition of c",
          secondary: "Only multipliers of tight constraints are positive.",
        },
      },
    ),
  },
  {
    id: "tdi-dual-2d-strong-duality",
    kicker: "Theorem 139 · Strong duality + complementary slackness",
    title: "The primal and integral dual values coincide",
    description:
      "The two selected right-hand sides are 3 and 4. Thus bᵀy*=3+4=7=cᵀx*. Complementary slackness is automatic because the positive multipliers sit only on constraints tight at x*.",
    formula: "cᵀx*=7=bᵀy*",
    insight:
      "Theorem 139 states the equivalence for every integral objective whose dual optimum exists and is finite—not just this example.",
    scene: scene2D(
      triangle2DTdiConstraints,
      [
        point2D([1, 2], "primal x*: value 7", "optimum"),
        label2D([0.0, 2.55], "dual: 1·3+1·4=7", "accent"),
        label2D([0.0, 2.25], "y* integral", "muted"),
      ],
      {
        viewport: { x: [-0.7, 2.8], y: [-0.7, 2.8] },
        caption: {
          primary: "Strong duality with an integral dual certificate",
          secondary: "Positive y-components correspond exactly to active inequalities.",
        },
      },
    ),
  },
];

const stages3D: VisualizationStage[] = [
  {
    id: "tdi-dual-3d-objective",
    kicker: "Chapter 23 · Theorem 139 · 3D",
    title: "The same dual interpretation is dimension-independent",
    description:
      "For the illustrative TDI cube P=[0,2]³, maximize c=(2,1,3). The unique optimum is x*=(2,2,2), where all three upper-bound rows e₁,e₂,e₃ are tight.",
    formula: "c=(2,1,3),   x*=(2,2,2),   cᵀx*=12",
    insight:
      "The cube example is not a separate theorem; it visualizes Theorem 139 in dimension three.",
    scene: scene3D({
      bounds: { x: [-0.5, 3.5], y: [-0.5, 3.5], z: [-0.5, 3.5] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.72, pitch: 0.5, distance: 6.5 },
      meshes: [boxMesh("dual-cube", [2, 2, 2], "P=[0,2]³")],
      markers: [
        ...integerBoxMarkers([2, 2, 2], "dual-cube-lattice"),
        marker3D("dual-cube-xstar", [2, 2, 2], "x*=(2,2,2)", "optimum", 0.11),
      ],
      segments: [
        segment3D("dual-c", [0, 0, 0], [1.2, 0.6, 1.8], "c=(2,1,3)", TDI_COLORS.rose),
      ],
      caption: {
        primary: "Integral objective over a 3D TDI system",
        secondary: "The objective points toward the upper vertex.",
      },
    }),
  },
  {
    id: "tdi-dual-3d-y",
    kicker: "Theorem 139 · Integral dual multipliers",
    title: "The objective coefficients themselves become normal multiplicities",
    description:
      "Since c=2e₁+e₂+3e₃, choose integral dual multipliers y*=(2,1,3) on the three upper-bound inequalities and zero on the three lower bounds.",
    formula: "Aᵀy*=c,   y*=(2,1,3,0,0,0)∈ℤ₊⁶",
    insight:
      "The dual variable records how many copies of each tight row are needed to build c.",
    scene: scene3D({
      bounds: { x: [-0.5, 4.2], y: [-0.5, 4.2], z: [-0.5, 5.2] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.72, pitch: 0.5, distance: 7.0 },
      meshes: [boxMesh("dual-cube-ghost", [2, 2, 2], "P", "ghost", 0.08)],
      markers: [marker3D("dual-cube-apex", [2, 2, 2], "optimal face", "optimum", 0.11)],
      segments: [
        segment3D("dual-e1", [2, 2, 2], [4, 2, 2], "2e₁", TDI_COLORS.orange),
        segment3D("dual-e2", [2, 2, 2], [2, 3, 2], "e₂", TDI_COLORS.aqua),
        segment3D("dual-e3", [2, 2, 2], [2, 2, 5], "3e₃", TDI_COLORS.violet),
      ],
      caption: {
        primary: "Integral decomposition of c by active normals",
        secondary: "2e₁+e₂+3e₃=c.",
      },
    }),
  },
  {
    id: "tdi-dual-3d-value",
    kicker: "Theorem 139 · Matching values",
    title: "The integral dual certificate has the same objective value",
    description:
      "Each upper-bound right-hand side equals two, so bᵀy*=2·2+2·1+2·3=12, matching cᵀx*=12.",
    formula: "bᵀy*=12=cᵀx*",
    insight:
      "The equality combines strong LP duality with the integrality guarantee supplied by TDI.",
    scene: scene3D({
      bounds: { x: [-0.5, 3.4], y: [-0.5, 3.4], z: [-0.5, 3.4] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.72, pitch: 0.5, distance: 6.5 },
      meshes: [boxMesh("dual-cube-final", [2, 2, 2], "P=[0,2]³")],
      markers: [marker3D("dual-cube-final-x", [2, 2, 2], "primal value 12", "optimum", 0.11)],
      caption: {
        primary: "Integral dual optimum",
        secondary: "Theorem 139: this phenomenon holds for every integral c with finite optimum.",
      },
    }),
  },
];

const examples: VisualizationExample[] = [
  { id: "tdi-dual-2d", title: "2D · Triangle", stages: stages2D },
  { id: "tdi-dual-3d", title: "3D · Cube", stages: stages3D },
];

const visualization: VisualizationDefinition = {
  id: "tdi-integral-dual-optima",
  title: "TDI II — Integral Dual Optimal Solutions",
  shortTitle: "TDI ↔ integral dual optimum",
  chapter: "Total dual integrality",
  order: 2,
  description:
    "Theorem 139: TDI is equivalent to the existence of an integral optimal dual vector for every integral objective with a finite dual optimum.",
  difficulty: "Advanced",
  duration: 13,
  accent: TDI_COLORS.aqua,
  controls: { constraints: true, grid: true, lattice: true, vertices: true, labels: true },
  stages: stages2D,
  examples,
  proof: {
    title: "Theorem 139 in one chain",
    steps: [
      "An integral objective c attaining its optimum on face F lies in the cone of the rows tight on F.",
      "TDI expresses c as a nonnegative integer combination of those rows; use the coefficients as y* and set all other dual coordinates to zero.",
      "Complementary slackness makes y* optimal.",
      "Conversely, an integral optimal dual y* for an objective exposing F has zero entries off F and therefore gives the required integral row representation of c.",
    ],
  },
};

export default visualization;
