import type { Constraint, Primitive } from "@/engine/types";
import type {
  VisualizationDefinition,
  VisualizationExample,
  VisualizationStage,
} from "@/visualizations/types";
import {
  TDI_COLORS,
  label2D,
  marker3D,
  point2D,
  scene2D,
  scene3D,
  segment3D,
  theorem143IntegerMarkers,
  theorem143Mesh,
} from "@/visualizations/helpers/tdi-scenes";

const constraints2D: Constraint[] = [
  { id: "t143-capacity", a: 1, b: 2, limit: 5, label: "x₁+2x₂≤5", color: TDI_COLORS.orange },
  { id: "t143-x2", a: 0, b: 1, limit: 2, label: "x₂≤2", color: TDI_COLORS.violet },
  { id: "t143-x1nonneg", a: -1, b: 0, limit: 0, label: "−x₁≤0", color: TDI_COLORS.aqua },
  { id: "t143-x2nonneg", a: 0, b: -1, limit: 0, label: "−x₂≤0", color: TDI_COLORS.aqua },
];

const vertices2D: Array<[number, number]> = [[0,0],[5,0],[1,2],[0,2]];

const stages2D: VisualizationStage[] = [
  {
    id: "tdi-143-2d-system",
    kicker: "Chapter 23 · Theorem 143 · 2D",
    title: "Divisibility creates a triangular hierarchy of inequalities",
    description:
      "Take a₁=1, a₂=2, b=5. Because a₂ is an integer multiple of a₁, system (60) becomes x₁+2x₂≤5, x₂≤2, and x≥0.",
    formula: "a₁=1, a₂=2, b=5  ⇒  x₁+2x₂≤5, x₂≤⌊5/2⌋=2, x≥0",
    insight:
      "Theorem 143 proves this system is TDI for every positive divisible chain a₁|a₂|⋯|aₙ.",
    scene: scene2D(
      constraints2D,
      vertices2D.map<Primitive>((at, index) => point2D(at, index === 2 ? "(1,2)" : undefined, "integer")),
      {
        viewport: { x: [-0.6, 5.8], y: [-0.6, 3.0] },
        caption: {
          primary: "Theorem 143 in dimension two",
          secondary: "Nested knapsack-style bounds generated by a₁|a₂.",
        },
      },
    ),
  },
  {
    id: "tdi-143-2d-dual-forward",
    kicker: "Theorem 143 · Forward construction of y*",
    title: "The proof recursively constructs an integral dual solution",
    description:
      "For the integral objective c=(1,3), the theorem sets y₁*=max{0,c₁}=1 and y₂*=max{0,c₂−2y₁*}=1. Integrality is preserved because the coefficient ratio a₂/a₁=2 is integral.",
    formula: "y₁*=1,   y₂*=max{0,3−2}=1",
    insight:
      "This is the direct dual-side proof of TDI promised by Theorem 139: every integral objective receives an integral optimal dual certificate.",
    scene: scene2D(
      constraints2D,
      [
        point2D([1,2], "candidate optimum", "optimum"),
        label2D([2.5,2.55], "c=(1,3)", "accent"),
        label2D([2.5,2.25], "y*=(1,1)", "accent"),
      ],
      {
        viewport: { x: [-0.6, 5.8], y: [-0.6, 3.0] },
        objective: { vector: [1,3], label: "c=(1,3)" },
        caption: {
          primary: "Forward dual recursion",
          secondary: "Integral c and integral ratios keep y* integral.",
        },
      },
    ),
  },
  {
    id: "tdi-143-2d-primal-backward",
    kicker: "Theorem 143 · Backward construction of x*",
    title: "Positive dual multipliers select tight primal inequalities",
    description:
      "Since y₂*>0, set x₂*=⌊5/2⌋=2. Since y₁*>0, set x₁*=5−2x₂*=1. The constructed primal point is integral and complementary to y*.",
    formula: "x₂*=2,   x₁*=5−2·2=1",
    insight:
      "The proof simultaneously constructs feasible integral primal and dual vectors satisfying complementary slackness.",
    scene: scene2D(
      constraints2D,
      [
        point2D([1,2], "x*=(1,2)", "optimum"),
        label2D([2.4,2.55], "both upper inequalities tight", "accent"),
      ],
      {
        viewport: { x: [-0.6, 5.8], y: [-0.6, 3.0] },
        caption: {
          primary: "Backward primal recursion",
          secondary: "yᵢ*>0 forces the corresponding nested inequality to equality.",
        },
      },
    ),
  },
  {
    id: "tdi-143-2d-values",
    kicker: "Theorem 143 · Complementarity",
    title: "The integral primal and dual values match",
    description:
      "The primal value is cᵀx*=1·1+3·2=7. The dual objective is 5y₁*+2y₂*=5+2=7.",
    formula: "cᵀx*=7=bᵀy*",
    insight:
      "This explicit equality completes the TDI certificate for the chosen objective; the theorem's recursion works for every integral c.",
    scene: scene2D(
      constraints2D,
      [
        point2D([1,2], "primal value 7", "optimum"),
        label2D([2.3,2.45], "dual value 5+2=7", "accent"),
      ],
      {
        viewport: { x: [-0.6, 5.8], y: [-0.6, 3.0] },
        caption: {
          primary: "Integral optimal primal–dual pair",
          secondary: "Theorem 143 gives such a pair for every integral objective.",
        },
      },
    ),
  },
];

const stages3D: VisualizationStage[] = [
  {
    id: "tdi-143-3d-system",
    kicker: "Chapter 23 · Theorem 143 · 3D",
    title: "Use the chain 1|2|4 in three dimensions",
    description:
      "Set a=(1,2,4) and b=7. System (60) becomes x₁+2x₂+4x₃≤7, x₂+2x₃≤3, x₃≤1, and x≥0.",
    formula: "x₁+2x₂+4x₃≤7,   x₂+2x₃≤3,   x₃≤1,   x≥0",
    insight:
      "The nested constraints are the exact n=3 specialization of Theorem 143.",
    scene: scene3D({
      bounds: { x: [-0.6, 7.8], y: [-0.6, 3.8], z: [-0.4, 1.8] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.75, pitch: 0.42, distance: 8.8 },
      meshes: [theorem143Mesh("t143-polytope", "Theorem 143 feasible polytope")],
      markers: theorem143IntegerMarkers(),
      caption: {
        primary: "Theorem 143 polytope for a=(1,2,4), b=7",
        secondary: "All displayed lattice points satisfy the nested inequalities.",
      },
    }),
  },
  {
    id: "tdi-143-3d-dual-forward",
    kicker: "Theorem 143 · Forward dual recursion",
    title: "An integral objective generates integral dual multipliers recursively",
    description:
      "Choose c=(1,3,8). Then y₁*=1, y₂*=3−2·1=1, and y₃*=8−4·1−2·1=2. All are positive integers.",
    formula: "y*=(1,1,2)",
    insight:
      "The integer divisibility ratios 2 and 4/2=2 are exactly what keep the recursion in ℤ.",
    scene: scene3D({
      bounds: { x: [-0.6, 7.8], y: [-0.6, 3.8], z: [-0.4, 2.4] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.75, pitch: 0.42, distance: 8.8 },
      meshes: [theorem143Mesh("t143-polytope-dual", "P")],
      markers: [marker3D("t143-dual-target", [1,1,1], "eventual x*", "optimum", 0.1)],
      segments: [
        segment3D("t143-c", [0,0,0], [1,1.5,2], "c=(1,3,8) scaled", TDI_COLORS.rose),
      ],
      caption: {
        primary: "Forward recursion y₁*,y₂*,y₃*",
        secondary: "(1,1,2) is integral and dual-feasible.",
      },
    }),
  },
  {
    id: "tdi-143-3d-primal-backward",
    kicker: "Theorem 143 · Backward primal recursion",
    title: "The positive y-components make all three nested upper inequalities tight",
    description:
      "Because y₃*>0, x₃*=⌊7/4⌋=1. Then x₂*=⌊7/2⌋−2x₃*=3−2=1. Finally x₁*=7−2x₂*−4x₃*=1.",
    formula: "x*=(1,1,1)",
    insight:
      "The recursion moves backward from the coarsest divisible weight to the finest one.",
    scene: scene3D({
      bounds: { x: [-0.6, 7.8], y: [-0.6, 3.8], z: [-0.4, 1.8] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.75, pitch: 0.42, distance: 8.8 },
      meshes: [theorem143Mesh("t143-polytope-primal", "P")],
      markers: [
        ...theorem143IntegerMarkers(),
        marker3D("t143-xstar", [1,1,1], "x*=(1,1,1)", "optimum", 0.11),
      ],
      caption: {
        primary: "Backward recursion constructs x*",
        secondary: "All three nested upper bounds are tight at x*.",
      },
    }),
  },
  {
    id: "tdi-143-3d-values",
    kicker: "Theorem 143 · TDI certificate",
    title: "Primal and integral dual values coincide at 12",
    description:
      "The primal value is 1+3+8=12. The dual value is 7·1+3·1+1·2=12. Thus the constructed pair is optimal by complementary slackness.",
    formula: "cᵀx*=12=7y₁*+3y₂*+y₃*=bᵀy*",
    insight:
      "This concrete 3D run mirrors the proof in the notes line by line.",
    scene: scene3D({
      bounds: { x: [-0.6, 7.8], y: [-0.6, 3.8], z: [-0.4, 1.8] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.75, pitch: 0.42, distance: 8.8 },
      meshes: [theorem143Mesh("t143-polytope-final", "P")],
      markers: [marker3D("t143-xstar-final", [1,1,1], "value 12", "optimum", 0.11)],
      caption: {
        primary: "Integral primal–dual optimum",
        secondary: "The recursion proves system (60) is TDI.",
      },
    }),
  },
];

const examples: VisualizationExample[] = [
  {
    id: "tdi-143-2d",
    title: "2D · a=(1,2), b=5",
    description: "A complete two-variable run of the primal–dual recursion in Theorem 143.",
    stages: stages2D,
  },
  {
    id: "tdi-143-3d",
    title: "3D · a=(1,2,4), b=7",
    description: "A genuine 3D specialization of system (60) and its recursive optimal primal–dual pair.",
    stages: stages3D,
  },
];

const visualization: VisualizationDefinition = {
  id: "tdi-divisible-coefficient-system",
  title: "TDI V — The Divisible-Coefficient System",
  shortTitle: "Theorem 143",
  chapter: "Total dual integrality",
  order: 5,
  description:
    "Theorem 143: when a₁|a₂|⋯|aₙ, the nested system (60) is TDI; the proof explicitly constructs integral optimal dual and primal solutions by forward and backward recursions.",
  difficulty: "Advanced",
  duration: 14,
  accent: TDI_COLORS.lime,
  controls: { constraints: true, grid: true, lattice: true, vertices: true, labels: true },
  stages: stages2D,
  examples,
  proof: {
    title: "Theorem 143 recursion",
    steps: [
      "For integral c, define y₁*=max{0,c₁} and then yᵢ*=max{0,cᵢ−Σ_{j<i}(aᵢ/aⱼ)yⱼ*}. Divisibility makes every yᵢ* integral.",
      "Construct x* backward: if yᵢ*>0, make the i-th nested inequality tight; otherwise set xᵢ*=0.",
      "The resulting x* and y* are feasible and integral.",
      "Their complementary slackness conditions hold by construction, so they are optimal. Theorem 139 then yields TDI.",
    ],
  },
};

export default visualization;
