import type { Primitive } from "@/engine/types";
import type {
  VisualizationDefinition,
  VisualizationExample,
  VisualizationStage,
} from "@/visualizations/types";
import {
  TDI_COLORS,
  boxMesh,
  integerBoxMarkers,
  marker3D,
  point2D,
  scene2D,
  scene3D,
  segment3D,
  triangle2DTdiConstraints,
  triangle2DVertexMarkers,
  vector2D,
} from "@/visualizations/helpers/tdi-scenes";

const apex: [number, number] = [1, 2];
const apexNormals: Array<[number, number]> = [
  [-2, 1], [-1, 1], [0, 1], [1, 1], [2, 1],
];

const stages2D: VisualizationStage[] = [
  {
    id: "tdi-def-2d-polytope",
    kicker: "Chapter 23 · Definition 138 · 2D",
    title: "TDI is checked face by face through the tight rows",
    description:
      "Use the triangle P=conv{(0,0),(1,2),(2,0)} with the TDI description from Problem 12.1. At a face F, collect exactly the rows that are tight on F and inspect the cone generated by those row vectors.",
    formula: "Ax≤b is TDI ⇔ for every nonempty face F, {aᵢ:i∈I(F)} integrally generates cone({aᵢ:i∈I(F)})∩ℤⁿ",
    insight:
      "The property is local in the face lattice, but the object being generated lives in the normal-vector space.",
    scene: scene2D(
      triangle2DTdiConstraints,
      triangle2DVertexMarkers(),
      {
        viewport: { x: [-0.7, 2.7], y: [-0.7, 2.8] },
        caption: {
          primary: "A TDI description of the triangle",
          secondary: "Redundant inequalities are allowed and can be essential.",
        },
      },
    ),
  },
  {
    id: "tdi-def-2d-apex",
    kicker: "Definition 138 · Focus on one minimal face",
    title: "At the apex, five tight normals form the integral basis of the normal cone",
    description:
      "At (1,2), the tight rows are (−2,1),(−1,1),(0,1),(1,1),(2,1). The exercise identifies these as the integral basis of the cone generated by the two outer facet normals.",
    formula: "H={(−2,1),(−1,1),(0,1),(1,1),(2,1)}",
    insight:
      "The three redundant inequalities insert exactly the missing integer directions between the two extreme normals.",
    scene: scene2D(
      triangle2DTdiConstraints,
      [
        ...triangle2DVertexMarkers(),
        point2D(apex, "F={(1,2)}", "optimum"),
        ...apexNormals.map<Primitive>((normal, index) =>
          vector2D(
            apex,
            [apex[0] + 0.35 * normal[0], apex[1] + 0.35 * normal[1]],
            index === 0 ? "tight-row cone" : "",
            index === 0 || index === apexNormals.length - 1 ? TDI_COLORS.orange : TDI_COLORS.violet,
          ),
        ),
      ],
      {
        viewport: { x: [-0.7, 2.7], y: [-0.7, 3.5] },
        caption: {
          primary: "Translated normal cone at the apex",
          secondary: "The arrows are tight row vectors translated to start at the vertex.",
        },
      },
    ),
  },
  {
    id: "tdi-def-2d-other-faces",
    kicker: "Definition 138 · All faces",
    title: "The same test must hold at every other face",
    description:
      "At (0,0), the tight normal cone has integral basis {(0,−1),(−1,0),(−2,1)}. At (2,0), it has {(0,−1),(1,0),(2,1)}. Along an edge only the corresponding primitive row direction remains.",
    formula: "every nonempty face must pass the same integral-generation test",
    insight:
      "Checking only one vertex is not enough. TDI quantifies over the entire nonempty face structure.",
    scene: scene2D(
      triangle2DTdiConstraints,
      [
        point2D([0, 0], "{(0,−1),(−1,0),(−2,1)}", "optimum"),
        point2D([2, 0], "{(0,−1),(1,0),(2,1)}", "optimum"),
        point2D([1, 2], "five-generator apex cone", "optimum"),
      ],
      {
        viewport: { x: [-0.8, 2.8], y: [-0.8, 2.8] },
        caption: {
          primary: "Every minimal face has an integral normal generating set",
          secondary: "This is precisely the geometric TDI condition.",
        },
      },
    ),
  },
];

const cubeNormals: Array<[number, number, number]> = [
  [1, 0, 0], [0, 1, 0], [0, 0, 1],
];

const stages3D: VisualizationStage[] = [
  {
    id: "tdi-def-3d-cube",
    kicker: "Chapter 23 · Definition 138 · 3D",
    title: "In three dimensions, a vertex carries a three-dimensional normal cone",
    description:
      "Consider P=[0,2]³ described by −xᵢ≤0 and xᵢ≤2. At the upper vertex v=(2,2,2), the three upper-bound rows e₁,e₂,e₃ are tight.",
    formula: "I(v)={x₁≤2,x₂≤2,x₃≤2}",
    insight:
      "This 3D example is an illustrative application of Definition 138. The lecture theorem is dimension-independent.",
    scene: scene3D({
      bounds: { x: [-0.6, 3.5], y: [-0.6, 3.5], z: [-0.6, 3.5] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.72, pitch: 0.48, distance: 6.5 },
      meshes: [boxMesh("tdi-cube", [2, 2, 2], "P=[0,2]³")],
      markers: [
        ...integerBoxMarkers([2, 2, 2], "tdi-cube-lattice"),
        marker3D("tdi-cube-v", [2, 2, 2], "v=(2,2,2)", "optimum", 0.11),
      ],
      showIntegerLattice: false,
      caption: {
        primary: "A 3D face-cone test",
        secondary: "At v, the active rows are e₁,e₂,e₃.",
      },
    }),
  },
  {
    id: "tdi-def-3d-normal-cone",
    kicker: "Definition 138 · 3D normal cone",
    title: "The active rows integrally generate the full positive orthant",
    description:
      "Every integer point c in cone{e₁,e₂,e₃}=ℝ³₊ has the unique representation c=c₁e₁+c₂e₂+c₃e₃ with cᵢ∈ℤ₊.",
    formula: "cone{e₁,e₂,e₃}∩ℤ³=ℤ³₊",
    insight:
      "Here no redundant normals are needed because the active rows already form a unimodular basis.",
    scene: scene3D({
      bounds: { x: [-0.6, 4.0], y: [-0.6, 4.0], z: [-0.6, 4.0] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.72, pitch: 0.48, distance: 6.8 },
      meshes: [boxMesh("tdi-cube-ghost", [2, 2, 2], "P", "ghost", 0.08)],
      markers: [marker3D("tdi-cube-v2", [2, 2, 2], "v", "optimum", 0.11)],
      segments: cubeNormals.map((normal, index) =>
        segment3D(
          `tdi-cube-normal-${index}`,
          [2, 2, 2],
          [2 + normal[0], 2 + normal[1], 2 + normal[2]],
          `e${index + 1}`,
          [TDI_COLORS.orange, TDI_COLORS.aqua, TDI_COLORS.violet][index],
        ),
      ),
      caption: {
        primary: "Translated normal cone at v",
        secondary: "The cone is the positive orthant in dual coordinates.",
      },
    }),
  },
  {
    id: "tdi-def-3d-face-hierarchy",
    kicker: "Definition 138 · Faces of all dimensions",
    title: "Edges and facets inherit smaller coordinate orthants",
    description:
      "On a facet only one primitive normal is tight; on an edge two are tight; at a vertex three are tight. Each such coordinate cone is integrally generated by its active rows.",
    formula: "facet: 1 generator · edge: 2 generators · vertex: 3 generators",
    insight:
      "The cube passes Definition 138 simultaneously on every nonempty face.",
    scene: scene3D({
      bounds: { x: [-0.6, 3.4], y: [-0.6, 3.4], z: [-0.6, 3.4] },
      axisLabels: { x: "x₁", y: "x₂", z: "x₃" },
      camera: { yaw: -0.72, pitch: 0.48, distance: 6.5 },
      meshes: [boxMesh("tdi-cube-faces", [2, 2, 2], "P=[0,2]³")],
      markers: [
        marker3D("facet-point", [2, 1, 1], "facet: {e₁}", "integer"),
        marker3D("edge-point", [2, 2, 1], "edge: {e₁,e₂}", "integer"),
        marker3D("vertex-point", [2, 2, 2], "vertex: {e₁,e₂,e₃}", "optimum"),
      ],
      caption: {
        primary: "The face hierarchy and its active row sets",
        secondary: "Every active-row cone is an integral coordinate cone.",
      },
    }),
  },
];

const examples: VisualizationExample[] = [
  {
    id: "tdi-face-cones-2d",
    title: "2D · Triangle from Problem 12.1",
    description: "The exact two-dimensional TDI construction from the exercise solution.",
    stages: stages2D,
  },
  {
    id: "tdi-face-cones-3d",
    title: "3D · Cube",
    description: "A dimension-three illustration of the same face-cone criterion.",
    stages: stages3D,
  },
];

const visualization: VisualizationDefinition = {
  id: "tdi-face-cone-criterion",
  title: "TDI I — Face Cones and Integral Generating Sets",
  shortTitle: "TDI face-cone criterion",
  chapter: "Total dual integrality",
  order: 1,
  description:
    "Definition 138: a system is TDI exactly when, on every nonempty face, the tight row vectors integrally generate all lattice points in their cone.",
  difficulty: "Advanced",
  duration: 14,
  accent: TDI_COLORS.violet,
  controls: { constraints: true, grid: true, lattice: true, vertices: true, labels: true },
  stages: stages2D,
  examples,
  proof: {
    title: "Definition 138 checklist",
    steps: [
      "Choose a nonempty face F and its tight-row index set I(F).",
      "Form the cone generated by the tight row vectors aᵢ, i∈I(F).",
      "Check that every integer point in that cone is a nonnegative integer combination of those same rows.",
      "Repeat for every nonempty face.",
    ],
  },
};

export default visualization;
