// This file is generated by scripts/generate-visualization-registry.mjs.
// Add visualization modules under visualizations/<chapter>/ and run npm run dev or npm run build.

import visualization0 from "./cutting-planes/cone-split";
import visualization1 from "./cutting-planes/gomory-fractional-cut";
import visualization2 from "./cutting-planes/lift-and-project";
import visualization3 from "./cutting-planes/repeated-split-closures";
import visualization4 from "./cutting-planes/split-closure";
import visualization5 from "./cutting-planes/split-inequality-14";
import visualization6 from "./cutting-planes/split-inequality-description";
import visualization7 from "./cutting-planes/split-membership-characterization";
import visualization8 from "./extreme-ray-proximity/lemma-32-extreme-ray-bound";
import visualization9 from "./extreme-ray-proximity/lemma-32-proof-walkthrough";
import visualization10 from "./extreme-ray-proximity/lemma-51-multiplier-bound";
import visualization11 from "./extreme-ray-proximity/lemma-51-proof-walkthrough";
import visualization12 from "./extreme-ray-proximity/sign-compatible-cone";
import visualization13 from "./extreme-ray-proximity/theorem-34-lp-ip-proximity";
import visualization14 from "./extreme-ray-proximity/theorem-34-proof-walkthrough";
import visualization15 from "./extreme-ray-proximity/theorem-35-local-improvement";
import visualization16 from "./extreme-ray-proximity/theorem-35-proof-walkthrough";
import visualization17 from "./formulations/facility-location-formulations";
import visualization18 from "./graphs/graph-definitions-and-branchings";
import visualization19 from "./graphs/max-flow-min-cut-primal-dual";
import visualization20 from "./graphs/mst-greedy-and-dual-flooding";
import visualization21 from "./integral-generating-sets/integral-generating-sets-three-dimensional";
import visualization22 from "./integral-generating-sets/integral-generating-sets";
import visualization23 from "./lattice-free-polyhedra/doignon-sharpness-example-145";
import visualization24 from "./lattice-free-polyhedra/doignon-theorem-144";
import visualization25 from "./lattice-free-polyhedra/lemma-148-projection-product";
import visualization26 from "./lattice-free-polyhedra/lovasz-lemma-149";
import visualization27 from "./lattice-free-polyhedra/theorem-146-sparse-optimality-certificate";
import visualization28 from "./lattice-free-polyhedra/zn-free-definition-147";
import visualization29 from "./lattice-theory/approximate-nearest-vector-anv";
import visualization30 from "./lattice-theory/fixip-algorithm";
import visualization31 from "./lattice-theory/gram-schmidt-lll-reduction";
import visualization32 from "./lattice-theory/lattice-foundations";
import visualization33 from "./lattice-theory/minkowski-convex-body-theorem";
import visualization34 from "./lattice-theory/voronoi-cells";
import visualization35 from "./lp-duality/dual-linear-program";
import visualization36 from "./lp-duality/dual-polyhedron";
import visualization37 from "./lp-duality/farkas-lemma";
import visualization38 from "./lp-duality/strong-complementary-slackness";
import visualization39 from "./polyhedra/ellipsoid-matrix-geometry";
import visualization40 from "./polyhedra/ellipsoid-representation";
import visualization41 from "./polyhedra/polyhedron-geometry.visualization";
import visualization42 from "./polyhedral-ties/finite-t-cone-examples";
import visualization43 from "./total-dual-integrality/tdi-divisible-coefficients";
import visualization44 from "./total-dual-integrality/tdi-dual-optima";
import visualization45 from "./total-dual-integrality/tdi-face-cones";
import visualization46 from "./total-dual-integrality/tdi-implies-integral-polyhedron";
import visualization47 from "./total-dual-integrality/tdi-representation-construction";
import visualization48 from "./total-unimodularity/affine-tu-decomposition";
import visualization49 from "./total-unimodularity/integer-decomposition-property";
import visualization50 from "./total-unimodularity/tu-unimodular-polyhedra";

export const generatedVisualizations = [
  visualization0,
  visualization1,
  visualization2,
  visualization3,
  visualization4,
  visualization5,
  visualization6,
  visualization7,
  visualization8,
  visualization9,
  visualization10,
  visualization11,
  visualization12,
  visualization13,
  visualization14,
  visualization15,
  visualization16,
  visualization17,
  visualization18,
  visualization19,
  visualization20,
  visualization21,
  visualization22,
  visualization23,
  visualization24,
  visualization25,
  visualization26,
  visualization27,
  visualization28,
  visualization29,
  visualization30,
  visualization31,
  visualization32,
  visualization33,
  visualization34,
  visualization35,
  visualization36,
  visualization37,
  visualization38,
  visualization39,
  visualization40,
  visualization41,
  visualization42,
  visualization43,
  visualization44,
  visualization45,
  visualization46,
  visualization47,
  visualization48,
  visualization49,
  visualization50,
];
