// This file is generated by scripts/generate-visualization-registry.mjs.
// Add visualization modules under visualizations/<chapter>/ and run npm run dev or npm run build.

import visualization0 from "./cutting-planes/cone-split";
import visualization1 from "./cutting-planes/lift-and-project";
import visualization2 from "./cutting-planes/repeated-split-closures";
import visualization3 from "./cutting-planes/split-closure";
import visualization4 from "./cutting-planes/split-inequality-14";
import visualization5 from "./cutting-planes/split-inequality-description";
import visualization6 from "./cutting-planes/split-membership-characterization";
import visualization7 from "./extreme-ray-proximity/lemma-32-extreme-ray-bound";
import visualization8 from "./extreme-ray-proximity/lemma-32-proof-walkthrough";
import visualization9 from "./extreme-ray-proximity/lemma-51-multiplier-bound";
import visualization10 from "./extreme-ray-proximity/lemma-51-proof-walkthrough";
import visualization11 from "./extreme-ray-proximity/sign-compatible-cone";
import visualization12 from "./extreme-ray-proximity/theorem-34-lp-ip-proximity";
import visualization13 from "./extreme-ray-proximity/theorem-34-proof-walkthrough";
import visualization14 from "./extreme-ray-proximity/theorem-35-local-improvement";
import visualization15 from "./extreme-ray-proximity/theorem-35-proof-walkthrough";
import visualization16 from "./formulations/facility-location-formulations";
import visualization17 from "./graphs/graph-definitions-and-branchings";
import visualization18 from "./graphs/mst-greedy-and-dual-flooding";
import visualization19 from "./lp-duality/dual-linear-program";
import visualization20 from "./lp-duality/dual-polyhedron";
import visualization21 from "./lp-duality/farkas-lemma";
import visualization22 from "./lp-duality/strong-complementary-slackness";
import visualization23 from "./polyhedra/polyhedron-geometry.visualization";
import visualization24 from "./polyhedral-ties/finite-t-cone-examples";
import visualization25 from "./total-unimodularity/affine-tu-decomposition";
import visualization26 from "./total-unimodularity/integer-decomposition-property";
import visualization27 from "./total-unimodularity/tu-unimodular-polyhedra";

export const generatedVisualizations = [
  visualization0,
  visualization1,
  visualization2,
  visualization3,
  visualization4,
  visualization5,
  visualization6,
  visualization7,
  visualization8,
  visualization9,
  visualization10,
  visualization11,
  visualization12,
  visualization13,
  visualization14,
  visualization15,
  visualization16,
  visualization17,
  visualization18,
  visualization19,
  visualization20,
  visualization21,
  visualization22,
  visualization23,
  visualization24,
  visualization25,
  visualization26,
  visualization27,
];
